import json

# ── BILLING (Subscription page) ───────────────────────────────────────────────
BILLING = {
    "ru": {
        "pageTitle": "Подписка",
        "pageDesc": "Управление вашим тарифным планом и историей платежей",
        "currentPlan": "Текущий план",
        "statusFree": "Бесплатный",
        "statusActive": "Активен",
        "expiresAt": "Действует до {{date}}",
        "current": "Текущий",
        "activated": "Активирован",
        "upgrade": "Перейти на этот план",
        "free": "Бесплатно",
        "perMonth": "мес",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Ожидает", "active": "Активна", "cancelled": "Отменена", "expired": "Истекла"},
        "feat": {
            "telegram": "Telegram-уведомления",
            "email": "Email-уведомления",
            "analytics": "Расширенная аналитика",
            "team": "Управление командой",
            "support": "Приоритетная поддержка",
            "clientsLimit": "До {{limit}} клиентов",
            "clientsUnlimited": "Неограниченно клиентов",
            "servicesLimit": "До {{limit}} услуг",
            "apptsLimit": "До {{limit}} записей в месяц",
            "apptsUnlimited": "Неограниченно записей",
            "clients50": "До 50 клиентов",
            "appts100": "До 100 записей в месяц"
        },
        "payDialog": {
            "title": "Выбор способа оплаты",
            "desc": "Оплата плана {{plan}} — {{price}} в месяц",
            "payme": "Оплатить через Payme",
            "click": "Оплатить через Click.uz",
            "notConfigured": "Платёжные провайдеры не настроены. Обратитесь к администратору.",
            "hint": "Вы будете перенаправлены на защищённую страницу оплаты"
        },
        "history": {"title": "История платежей"}
    },
    "en": {
        "pageTitle": "Subscription",
        "pageDesc": "Manage your plan and payment history",
        "currentPlan": "Current plan",
        "statusFree": "Free",
        "statusActive": "Active",
        "expiresAt": "Active until {{date}}",
        "current": "Current",
        "activated": "Activated",
        "upgrade": "Upgrade to this plan",
        "free": "Free",
        "perMonth": "mo",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Pending", "active": "Active", "cancelled": "Cancelled", "expired": "Expired"},
        "feat": {
            "telegram": "Telegram notifications",
            "email": "Email notifications",
            "analytics": "Advanced analytics",
            "team": "Team management",
            "support": "Priority support",
            "clientsLimit": "Up to {{limit}} clients",
            "clientsUnlimited": "Unlimited clients",
            "servicesLimit": "Up to {{limit}} services",
            "apptsLimit": "Up to {{limit}} appointments/month",
            "apptsUnlimited": "Unlimited appointments",
            "clients50": "Up to 50 clients",
            "appts100": "Up to 100 appointments/month"
        },
        "payDialog": {
            "title": "Select payment method",
            "desc": "Pay for {{plan}} plan — {{price}} per month",
            "payme": "Pay via Payme",
            "click": "Pay via Click.uz",
            "notConfigured": "Payment providers not configured. Contact administrator.",
            "hint": "You will be redirected to a secure payment page"
        },
        "history": {"title": "Payment history"}
    },
    "uz": {
        "pageTitle": "Obuna",
        "pageDesc": "Tarif rejangiz va to'lov tarixini boshqarish",
        "currentPlan": "Joriy reja",
        "statusFree": "Bepul",
        "statusActive": "Faol",
        "expiresAt": "{{date}} gacha amal qiladi",
        "current": "Joriy",
        "activated": "Faollashtirilgan",
        "upgrade": "Ushbu rejaga o'tish",
        "free": "Bepul",
        "perMonth": "oy",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Kutilmoqda", "active": "Faol", "cancelled": "Bekor qilingan", "expired": "Muddati o'tgan"},
        "feat": {
            "telegram": "Telegram bildirishnomalar",
            "email": "Email bildirishnomalar",
            "analytics": "Kengaytirilgan tahlil",
            "team": "Jamoani boshqarish",
            "support": "Ustunlik qo'llab-quvvatlash",
            "clientsLimit": "{{limit}} gacha mijoz",
            "clientsUnlimited": "Cheksiz mijozlar",
            "servicesLimit": "{{limit}} gacha xizmat",
            "apptsLimit": "Oyiga {{limit}} gacha yozuv",
            "apptsUnlimited": "Cheksiz yozuvlar",
            "clients50": "50 gacha mijoz",
            "appts100": "Oyiga 100 gacha yozuv"
        },
        "payDialog": {
            "title": "To'lov usulini tanlash",
            "desc": "{{plan}} rejasi uchun to'lov — oyiga {{price}}",
            "payme": "Payme orqali to'lash",
            "click": "Click.uz orqali to'lash",
            "notConfigured": "To'lov provayderlari sozlanmagan. Administrator bilan bog'laning.",
            "hint": "Siz himoyalangan to'lov sahifasiga yo'naltirilasiz"
        },
        "history": {"title": "To'lov tarixi"}
    },
    "kz": {
        "pageTitle": "Жазылым",
        "pageDesc": "Тарифтік жоспарыңызды және төлем тарихын басқарыңыз",
        "currentPlan": "Ағымдағы жоспар",
        "statusFree": "Тегін",
        "statusActive": "Белсенді",
        "expiresAt": "{{date}} дейін жарамды",
        "current": "Ағымдағы",
        "activated": "Белсендірілген",
        "upgrade": "Осы жоспарға өту",
        "free": "Тегін",
        "perMonth": "ай",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Күтілуде", "active": "Белсенді", "cancelled": "Жойылды", "expired": "Мерзімі өтті"},
        "feat": {
            "telegram": "Telegram хабарландырулары",
            "email": "Email хабарландырулары",
            "analytics": "Кеңейтілген аналитика",
            "team": "Команданы басқару",
            "support": "Басымдықты қолдау",
            "clientsLimit": "{{limit}} дейін клиент",
            "clientsUnlimited": "Шексіз клиенттер",
            "servicesLimit": "{{limit}} дейін қызмет",
            "apptsLimit": "Айына {{limit}} дейін жазба",
            "apptsUnlimited": "Шексіз жазбалар",
            "clients50": "50 дейін клиент",
            "appts100": "Айына 100 дейін жазба"
        },
        "payDialog": {
            "title": "Төлем тәсілін таңдау",
            "desc": "{{plan}} жоспары үшін төлем — айына {{price}}",
            "payme": "Payme арқылы төлеу",
            "click": "Click.uz арқылы төлеу",
            "notConfigured": "Төлем провайдерлері орнатылмаған. Әкімшіге хабарласыңыз.",
            "hint": "Сіз қауіпсіз төлем бетіне бағытталасыз"
        },
        "history": {"title": "Төлем тарихы"}
    },
    "ky": {
        "pageTitle": "Жазылуу",
        "pageDesc": "Тарифтик планыңызды жана төлөм тарыхын башкарыңыз",
        "currentPlan": "Учурдагы план",
        "statusFree": "Акысыз",
        "statusActive": "Активдүү",
        "expiresAt": "{{date}} чейин жарактуу",
        "current": "Учурдагы",
        "activated": "Активдештирилген",
        "upgrade": "Бул планга өтүү",
        "free": "Акысыз",
        "perMonth": "ай",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Күтүлүүдө", "active": "Активдүү", "cancelled": "Жоюлду", "expired": "Мөөнөтү өттү"},
        "feat": {
            "telegram": "Telegram билдирүүлөр",
            "email": "Email билдирүүлөр",
            "analytics": "Кеңейтилген аналитика",
            "team": "Команданы башкаруу",
            "support": "Артыкчылыктуу колдоо",
            "clientsLimit": "{{limit}} чейин кардар",
            "clientsUnlimited": "Чексиз кардарлар",
            "servicesLimit": "{{limit}} чейин кызмат",
            "apptsLimit": "Айына {{limit}} чейин жазуу",
            "apptsUnlimited": "Чексиз жазуулар",
            "clients50": "50 чейин кардар",
            "appts100": "Айына 100 чейин жазуу"
        },
        "payDialog": {
            "title": "Төлөм ыкмасын тандоо",
            "desc": "{{plan}} планы үчүн төлөм — айына {{price}}",
            "payme": "Payme аркылуу төлөө",
            "click": "Click.uz аркылуу төлөө",
            "notConfigured": "Төлөм провайдерлери орнотулган жок. Администратор менен байланышыңыз.",
            "hint": "Сиз коопсуз төлөм бетине багытталасыз"
        },
        "history": {"title": "Төлөм тарыхы"}
    },
    "tg": {
        "pageTitle": "Обуна",
        "pageDesc": "Нақшаи тарифии худро ва таърихи пардохтҳоро идора кунед",
        "currentPlan": "Нақшаи ҷорӣ",
        "statusFree": "Ройгон",
        "statusActive": "Фаъол",
        "expiresAt": "То {{date}} амал мекунад",
        "current": "Ҷорӣ",
        "activated": "Фаъол карда шуд",
        "upgrade": "Ба ин нақша гузаштан",
        "free": "Ройгон",
        "perMonth": "моҳ",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Интизор", "active": "Фаъол", "cancelled": "Бекор шуд", "expired": "Муддат гузашт"},
        "feat": {
            "telegram": "Огоҳиҳои Telegram",
            "email": "Огоҳиҳои Email",
            "analytics": "Таҳлили васеъ",
            "team": "Идоракунии даста",
            "support": "Дастгирии афзалиятнок",
            "clientsLimit": "То {{limit}} муштарӣ",
            "clientsUnlimited": "Муштариёни беҳад",
            "servicesLimit": "То {{limit}} хидмат",
            "apptsLimit": "То {{limit}} сабт дар моҳ",
            "apptsUnlimited": "Сабтҳои беҳад",
            "clients50": "То 50 муштарӣ",
            "appts100": "То 100 сабт дар моҳ"
        },
        "payDialog": {
            "title": "Интихоби усули пардохт",
            "desc": "Пардохт барои нақшаи {{plan}} — {{price}} дар моҳ",
            "payme": "Пардохт тавассути Payme",
            "click": "Пардохт тавассути Click.uz",
            "notConfigured": "Провайдерҳои пардохт танзим нашудаанд. Бо маъмур тамос гиред.",
            "hint": "Шумо ба саҳифаи пардохти бехатар равона мешавед"
        },
        "history": {"title": "Таърихи пардохтҳо"}
    },
    "by": {
        "pageTitle": "Падпіска",
        "pageDesc": "Кіруйце вашым тарыфным планам і гісторыяй плацяжоў",
        "currentPlan": "Бягучы план",
        "statusFree": "Бясплатны",
        "statusActive": "Актыўны",
        "expiresAt": "Дзейнічае да {{date}}",
        "current": "Бягучы",
        "activated": "Актываваны",
        "upgrade": "Перайсці на гэты план",
        "free": "Бясплатна",
        "perMonth": "мес",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Чакае", "active": "Актыўная", "cancelled": "Адменена", "expired": "Скончылася"},
        "feat": {
            "telegram": "Паведамленні Telegram",
            "email": "Паведамленні Email",
            "analytics": "Пашыраная аналітыка",
            "team": "Кіраванне камандай",
            "support": "Прыярытэтная падтрымка",
            "clientsLimit": "Да {{limit}} кліентаў",
            "clientsUnlimited": "Неабмежаваная колькасць кліентаў",
            "servicesLimit": "Да {{limit}} паслуг",
            "apptsLimit": "Да {{limit}} запісаў у месяц",
            "apptsUnlimited": "Неабмежаваная колькасць запісаў",
            "clients50": "Да 50 кліентаў",
            "appts100": "Да 100 запісаў у месяц"
        },
        "payDialog": {
            "title": "Выбар спосабу аплаты",
            "desc": "Аплата плана {{plan}} — {{price}} у месяц",
            "payme": "Аплаціць праз Payme",
            "click": "Аплаціць праз Click.uz",
            "notConfigured": "Правайдары аплаты не настроены. Звярніцеся да адміністратара.",
            "hint": "Вы будзеце перанакіраваны на абароненую старонку аплаты"
        },
        "history": {"title": "Гісторыя плацяжоў"}
    },
    "uk": {
        "pageTitle": "Підписка",
        "pageDesc": "Керуйте своїм тарифним планом та історією платежів",
        "currentPlan": "Поточний план",
        "statusFree": "Безкоштовний",
        "statusActive": "Активний",
        "expiresAt": "Діє до {{date}}",
        "current": "Поточний",
        "activated": "Активовано",
        "upgrade": "Перейти на цей план",
        "free": "Безкоштовно",
        "perMonth": "міс",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Очікує", "active": "Активна", "cancelled": "Скасовано", "expired": "Закінчилась"},
        "feat": {
            "telegram": "Сповіщення Telegram",
            "email": "Сповіщення Email",
            "analytics": "Розширена аналітика",
            "team": "Управління командою",
            "support": "Пріоритетна підтримка",
            "clientsLimit": "До {{limit}} клієнтів",
            "clientsUnlimited": "Необмежена кількість клієнтів",
            "servicesLimit": "До {{limit}} послуг",
            "apptsLimit": "До {{limit}} записів на місяць",
            "apptsUnlimited": "Необмежена кількість записів",
            "clients50": "До 50 клієнтів",
            "appts100": "До 100 записів на місяць"
        },
        "payDialog": {
            "title": "Вибір способу оплати",
            "desc": "Оплата плану {{plan}} — {{price}} на місяць",
            "payme": "Оплатити через Payme",
            "click": "Оплатити через Click.uz",
            "notConfigured": "Платіжні провайдери не налаштовані. Зверніться до адміністратора.",
            "hint": "Вас буде перенаправлено на захищену сторінку оплати"
        },
        "history": {"title": "Історія платежів"}
    },
    "kaa": {
        "pageTitle": "Jazılım",
        "pageDesc": "Tarif rejańızdı hám tólem tarixın basqarıń",
        "currentPlan": "Járamlı reja",
        "statusFree": "Tegin",
        "statusActive": "Aktiv",
        "expiresAt": "{{date}} shekem járamlı",
        "current": "Járamlı",
        "activated": "Aktivlestirilgen",
        "upgrade": "Bul rejaǵa ótiw",
        "free": "Tegin",
        "perMonth": "ay",
        "plan": {"free": "Free", "pro": "Pro", "enterprise": "Enterprise"},
        "status": {"pending": "Kútiliwde", "active": "Aktiv", "cancelled": "Bekar qılındı", "expired": "Merzimi ótken"},
        "feat": {
            "telegram": "Telegram xabarlawlar",
            "email": "Email xabarlawlar",
            "analytics": "Keńeytirilgen analitika",
            "team": "Komandanı basqarıw",
            "support": "Basımlı qollap-quwwatlaw",
            "clientsLimit": "{{limit}} shekem mijoz",
            "clientsUnlimited": "Sheksiz mijozlar",
            "servicesLimit": "{{limit}} shekem xizmet",
            "apptsLimit": "Ayına {{limit}} shekem jazıw",
            "apptsUnlimited": "Sheksiz jazıwlar",
            "clients50": "50 shekem mijoz",
            "appts100": "Ayına 100 shekem jazıw"
        },
        "payDialog": {
            "title": "Tólem usılın tańlaw",
            "desc": "{{plan}} rejası ushın tólem — ayına {{price}}",
            "payme": "Payme arqalı tólaw",
            "click": "Click.uz arqalı tólaw",
            "notConfigured": "Tólem provayderları sazlanbaǵan. Administratorǵa xabarlasıń.",
            "hint": "Siz qorǵalǵan tólem betine jiberilesiź"
        },
        "history": {"title": "Tólem tarixi"}
    }
}

# ── PROFILE TRANSFER keys ─────────────────────────────────────────────────────
TRANSFER = {
    "ru": {
        "transfer": "Перенос данных",
        "transferShare": "Поделиться данными",
        "transferShareDesc": "Создайте код — другой мастер сможет скопировать ваши услуги и склад",
        "transferShareStats": "Будет доступно: {{services}} усл., {{inventory}} тов.",
        "transferCreateCode": "Создать код",
        "transferCreating": "Создание...",
        "transferActiveCode": "Активный код",
        "transferExpires": "Истекает {{time}}",
        "transferRevoke": "Отозвать",
        "transferRevoking": "Отзыв...",
        "transferCodeCopied": "Код скопирован",
        "transferImport": "Импорт по коду",
        "transferImportDesc": "Введите код от другого мастера чтобы скопировать его услуги и склад",
        "transferTokenPlaceholder": "Введите код (12 символов)",
        "transferCheck": "Проверить",
        "transferChecking": "Проверка...",
        "transferFound": "Найдено для импорта",
        "transferServices": "Услуги",
        "transferInventory": "Склад",
        "transferStrategy": "При совпадении названий",
        "transferStrategySkip": "Добавить только новые",
        "transferStrategyReplace": "Заменить совпадающие",
        "transferImportBtn": "Импортировать",
        "transferImporting": "Импортируется...",
        "transferStepInventory": "Копирование склада...",
        "transferStepCategories": "Копирование категорий...",
        "transferStepServices": "Копирование услуг...",
        "transferStepMaterials": "Копирование материалов...",
        "transferStepDone": "Завершение...",
        "transferDone": "Импорт завершён",
        "transferNotFound": "Код не найден или истёк",
        "transferNoData": "Нечего копировать — у этого мастера нет услуг или товаров",
        "transferResultServices": "Услуг: +{{added}} новых, {{replaced}} заменено, {{skipped}} пропущено",
        "transferResultInventory": "Склад: +{{added}} новых, {{replaced}} заменено, {{skipped}} пропущено",
        "transferResultMaterials": "Материалов к услугам: {{added}}"
    },
    "en": {
        "transfer": "Data Transfer",
        "transferShare": "Share your data",
        "transferShareDesc": "Create a code — another master can copy your services and inventory",
        "transferShareStats": "Available: {{services}} services, {{inventory}} items",
        "transferCreateCode": "Create code",
        "transferCreating": "Creating...",
        "transferActiveCode": "Active code",
        "transferExpires": "Expires {{time}}",
        "transferRevoke": "Revoke",
        "transferRevoking": "Revoking...",
        "transferCodeCopied": "Code copied",
        "transferImport": "Import by code",
        "transferImportDesc": "Enter a code from another master to copy their services and inventory",
        "transferTokenPlaceholder": "Enter code (12 characters)",
        "transferCheck": "Verify",
        "transferChecking": "Checking...",
        "transferFound": "Found for import",
        "transferServices": "Services",
        "transferInventory": "Inventory",
        "transferStrategy": "On name conflict",
        "transferStrategySkip": "Add new only",
        "transferStrategyReplace": "Replace matching",
        "transferImportBtn": "Import",
        "transferImporting": "Importing...",
        "transferStepInventory": "Copying inventory...",
        "transferStepCategories": "Copying categories...",
        "transferStepServices": "Copying services...",
        "transferStepMaterials": "Copying materials...",
        "transferStepDone": "Finishing...",
        "transferDone": "Import complete",
        "transferNotFound": "Code not found or expired",
        "transferNoData": "Nothing to copy — this master has no services or items",
        "transferResultServices": "Services: +{{added}} new, {{replaced}} replaced, {{skipped}} skipped",
        "transferResultInventory": "Inventory: +{{added}} new, {{replaced}} replaced, {{skipped}} skipped",
        "transferResultMaterials": "Service materials: {{added}}"
    },
    "uz": {
        "transfer": "Ma'lumotlarni o'tkazish",
        "transferShare": "Ma'lumotlarni ulashish",
        "transferShareDesc": "Kod yarating — boshqa usta sizning xizmatlaringiz va omboringizni nusxalashi mumkin",
        "transferShareStats": "Mavjud: {{services}} xizmat, {{inventory}} tovar",
        "transferCreateCode": "Kod yaratish",
        "transferCreating": "Yaratilmoqda...",
        "transferActiveCode": "Faol kod",
        "transferExpires": "{{time}} da muddati tugaydi",
        "transferRevoke": "Bekor qilish",
        "transferRevoking": "Bekor qilinmoqda...",
        "transferCodeCopied": "Kod nusxalandi",
        "transferImport": "Kod bo'yicha import",
        "transferImportDesc": "Xizmatlar va omborni nusxalash uchun boshqa ustaning kodini kiriting",
        "transferTokenPlaceholder": "Kodni kiriting (12 belgi)",
        "transferCheck": "Tekshirish",
        "transferChecking": "Tekshirilmoqda...",
        "transferFound": "Import uchun topildi",
        "transferServices": "Xizmatlar",
        "transferInventory": "Ombor",
        "transferStrategy": "Nomlar mos kelganda",
        "transferStrategySkip": "Faqat yangilarini qo'shish",
        "transferStrategyReplace": "Mos kelganlarini almashtirish",
        "transferImportBtn": "Import qilish",
        "transferImporting": "Importlanmoqda...",
        "transferStepInventory": "Ombor nusxalanmoqda...",
        "transferStepCategories": "Kategoriyalar nusxalanmoqda...",
        "transferStepServices": "Xizmatlar nusxalanmoqda...",
        "transferStepMaterials": "Materiallar nusxalanmoqda...",
        "transferStepDone": "Yakunlanmoqda...",
        "transferDone": "Import yakunlandi",
        "transferNotFound": "Kod topilmadi yoki muddati o'tgan",
        "transferNoData": "Nusxalaydigan narsa yo'q — bu ustada xizmatlar yoki tovarlar yo'q",
        "transferResultServices": "Xizmatlar: +{{added}} yangi, {{replaced}} almashtirildi, {{skipped}} o'tkazib yuborildi",
        "transferResultInventory": "Ombor: +{{added}} yangi, {{replaced}} almashtirildi, {{skipped}} o'tkazib yuborildi",
        "transferResultMaterials": "Xizmatlarga materiallar: {{added}}"
    },
    "kz": {
        "transfer": "Деректерді тасымалдау",
        "transferShare": "Деректермен бөлісу",
        "transferShareDesc": "Код жасаңыз — басқа шебер сіздің қызметтеріңізді және қоймаңызды нусқалай алады",
        "transferShareStats": "Қол жетімді: {{services}} қызм., {{inventory}} тауар",
        "transferCreateCode": "Код жасау",
        "transferCreating": "Жасалуда...",
        "transferActiveCode": "Белсенді код",
        "transferExpires": "{{time}} мерзімі аяқталады",
        "transferRevoke": "Қайтарып алу",
        "transferRevoking": "Қайтарылуда...",
        "transferCodeCopied": "Код нусқаланды",
        "transferImport": "Код бойынша импорт",
        "transferImportDesc": "Қызметтер мен қойманы нусқалау үшін басқа шебердің кодін енгізіңіз",
        "transferTokenPlaceholder": "Кодті енгізіңіз (12 таңба)",
        "transferCheck": "Тексеру",
        "transferChecking": "Тексерілуде...",
        "transferFound": "Импорт үшін табылды",
        "transferServices": "Қызметтер",
        "transferInventory": "Қойма",
        "transferStrategy": "Аттар сәйкес келгенде",
        "transferStrategySkip": "Тек жаңаларын қосу",
        "transferStrategyReplace": "Сәйкестерін ауыстыру",
        "transferImportBtn": "Импорттау",
        "transferImporting": "Импортталуда...",
        "transferStepInventory": "Қойма нусқалануда...",
        "transferStepCategories": "Категориялар нусқалануда...",
        "transferStepServices": "Қызметтер нусқалануда...",
        "transferStepMaterials": "Материалдар нусқалануда...",
        "transferStepDone": "Аяқталуда...",
        "transferDone": "Импорт аяқталды",
        "transferNotFound": "Код табылмады немесе мерзімі өтті",
        "transferNoData": "Нусқалайтын ештеңе жоқ — бұл шеберде қызметтер немесе тауарлар жоқ",
        "transferResultServices": "Қызметтер: +{{added}} жаңа, {{replaced}} ауыстырылды, {{skipped}} өткізілді",
        "transferResultInventory": "Қойма: +{{added}} жаңа, {{replaced}} ауыстырылды, {{skipped}} өткізілді",
        "transferResultMaterials": "Қызметтерге материалдар: {{added}}"
    },
    "ky": {
        "transfer": "Маалыматтарды өткөрүү",
        "transferShare": "Маалыматтарды бөлүшүү",
        "transferShareDesc": "Код жасаңыз — башка чебер сиздин кызматтарыңызды жана кладыңызды нусхалай алат",
        "transferShareStats": "Жеткиликтүү: {{services}} кызм., {{inventory}} тауар",
        "transferCreateCode": "Код жасоо",
        "transferCreating": "Жасалууда...",
        "transferActiveCode": "Активдүү код",
        "transferExpires": "{{time}} мөөнөтү бүтөт",
        "transferRevoke": "Кайтаруу",
        "transferRevoking": "Кайтарылууда...",
        "transferCodeCopied": "Код нусхаланды",
        "transferImport": "Код боюнча импорт",
        "transferImportDesc": "Кызматтар менен кладды нусхалоо үчүн башка чебердин кодун киргизиңиз",
        "transferTokenPlaceholder": "Кодду киргизиңиз (12 белги)",
        "transferCheck": "Текшерүү",
        "transferChecking": "Текшерилүүдө...",
        "transferFound": "Импорт үчүн табылды",
        "transferServices": "Кызматтар",
        "transferInventory": "Склад",
        "transferStrategy": "Аттар дал келгенде",
        "transferStrategySkip": "Жаңыларын гана кошуу",
        "transferStrategyReplace": "Дал келгендерин алмаштыруу",
        "transferImportBtn": "Импорттоо",
        "transferImporting": "Импортталууда...",
        "transferStepInventory": "Склад нусхалануудa...",
        "transferStepCategories": "Категориялар нусхалануудa...",
        "transferStepServices": "Кызматтар нусхалануудa...",
        "transferStepMaterials": "Материалдар нусхалануудa...",
        "transferStepDone": "Аяктоодо...",
        "transferDone": "Импорт аяктады",
        "transferNotFound": "Код табылган жок же мөөнөтү өттү",
        "transferNoData": "Нусхалай турган эч нерсе жок — бул чебердин кызматтары же товарлары жок",
        "transferResultServices": "Кызматтар: +{{added}} жаңы, {{replaced}} алмаштырылды, {{skipped}} өткөрүлдү",
        "transferResultInventory": "Склад: +{{added}} жаңы, {{replaced}} алмаштырылды, {{skipped}} өткөрүлдү",
        "transferResultMaterials": "Кызматтарга материалдар: {{added}}"
    },
    "tg": {
        "transfer": "Интиқоли маълумот",
        "transferShare": "Мубодилаи маълумот",
        "transferShareDesc": "Код созед — устоди дигар метавонад хидматҳо ва анборатонро нусхабардорӣ кунад",
        "transferShareStats": "Дастрас: {{services}} хидм., {{inventory}} мол",
        "transferCreateCode": "Код сохтан",
        "transferCreating": "Сохта мешавад...",
        "transferActiveCode": "Коди фаъол",
        "transferExpires": "{{time}} муддат тамом мешавад",
        "transferRevoke": "Бозпас гирифтан",
        "transferRevoking": "Бозпас гирифта мешавад...",
        "transferCodeCopied": "Код нусхабардорӣ шуд",
        "transferImport": "Воридот аз рӯи код",
        "transferImportDesc": "Кодро аз устоди дигар ворид кунед то хидматҳо ва анборашро нусхабардорӣ кунед",
        "transferTokenPlaceholder": "Кодро ворид кунед (12 аломат)",
        "transferCheck": "Санҷидан",
        "transferChecking": "Санҷида мешавад...",
        "transferFound": "Барои воридот ёфт шуд",
        "transferServices": "Хидматҳо",
        "transferInventory": "Анбор",
        "transferStrategy": "Ҳангоми мувофиқати ном",
        "transferStrategySkip": "Танҳо навҳоро илова кунед",
        "transferStrategyReplace": "Мувофиқҳоро иваз кунед",
        "transferImportBtn": "Ворид кардан",
        "transferImporting": "Ворид карда мешавад...",
        "transferStepInventory": "Анбор нусхабардорӣ мешавад...",
        "transferStepCategories": "Категорияҳо нусхабардорӣ мешаванд...",
        "transferStepServices": "Хидматҳо нусхабардорӣ мешаванд...",
        "transferStepMaterials": "Маводҳо нусхабардорӣ мешаванд...",
        "transferStepDone": "Анҷом дода мешавад...",
        "transferDone": "Воридот анҷом ёфт",
        "transferNotFound": "Код ёфт нашуд ё муддат гузаштааст",
        "transferNoData": "Нусхабардорӣ кардан чизе нест — ин устод хидматҳо ё мол надорад",
        "transferResultServices": "Хидматҳо: +{{added}} нав, {{replaced}} иваз шуд, {{skipped}} гузашт",
        "transferResultInventory": "Анбор: +{{added}} нав, {{replaced}} иваз шуд, {{skipped}} гузашт",
        "transferResultMaterials": "Маводҳо барои хидматҳо: {{added}}"
    },
    "by": {
        "transfer": "Перанос даных",
        "transferShare": "Падзяліцца данымі",
        "transferShareDesc": "Стварыце код — іншы майстар зможа скапіраваць вашы паслугі і склад",
        "transferShareStats": "Будзе даступна: {{services}} пасл., {{inventory}} тавар.",
        "transferCreateCode": "Стварыць код",
        "transferCreating": "Стварэнне...",
        "transferActiveCode": "Актыўны код",
        "transferExpires": "Тэрмін заканчваецца {{time}}",
        "transferRevoke": "Адклікаць",
        "transferRevoking": "Адклікаецца...",
        "transferCodeCopied": "Код скапіраваны",
        "transferImport": "Імпарт па кодзе",
        "transferImportDesc": "Увядзіце код іншага майстра, каб скапіраваць яго паслугі і склад",
        "transferTokenPlaceholder": "Увядзіце код (12 сімвалаў)",
        "transferCheck": "Праверыць",
        "transferChecking": "Праверка...",
        "transferFound": "Знойдзена для імпарту",
        "transferServices": "Паслугі",
        "transferInventory": "Склад",
        "transferStrategy": "Пры супадзенні назваў",
        "transferStrategySkip": "Дадаць толькі новыя",
        "transferStrategyReplace": "Замяніць супадаючыя",
        "transferImportBtn": "Імпартаваць",
        "transferImporting": "Імпартуецца...",
        "transferStepInventory": "Капіраванне склада...",
        "transferStepCategories": "Капіраванне катэгорый...",
        "transferStepServices": "Капіраванне паслуг...",
        "transferStepMaterials": "Капіраванне матэрыялаў...",
        "transferStepDone": "Завяршэнне...",
        "transferDone": "Імпарт завершаны",
        "transferNotFound": "Код не знойдзены або тэрмін мінуў",
        "transferNoData": "Няма чаго капіраваць — у гэтага майстра няма паслуг або тавараў",
        "transferResultServices": "Паслугі: +{{added}} новых, {{replaced}} заменена, {{skipped}} прапушчана",
        "transferResultInventory": "Склад: +{{added}} новых, {{replaced}} заменена, {{skipped}} прапушчана",
        "transferResultMaterials": "Матэрыялы да паслуг: {{added}}"
    },
    "uk": {
        "transfer": "Перенос даних",
        "transferShare": "Поділитися даними",
        "transferShareDesc": "Створіть код — інший майстер зможе скопіювати ваші послуги та склад",
        "transferShareStats": "Буде доступно: {{services}} посл., {{inventory}} тов.",
        "transferCreateCode": "Створити код",
        "transferCreating": "Створення...",
        "transferActiveCode": "Активний код",
        "transferExpires": "Термін закінчується {{time}}",
        "transferRevoke": "Відкликати",
        "transferRevoking": "Відкликається...",
        "transferCodeCopied": "Код скопійовано",
        "transferImport": "Імпорт за кодом",
        "transferImportDesc": "Введіть код від іншого майстра, щоб скопіювати його послуги та склад",
        "transferTokenPlaceholder": "Введіть код (12 символів)",
        "transferCheck": "Перевірити",
        "transferChecking": "Перевірка...",
        "transferFound": "Знайдено для імпорту",
        "transferServices": "Послуги",
        "transferInventory": "Склад",
        "transferStrategy": "При збігу назв",
        "transferStrategySkip": "Додати тільки нові",
        "transferStrategyReplace": "Замінити збіжні",
        "transferImportBtn": "Імпортувати",
        "transferImporting": "Імпортується...",
        "transferStepInventory": "Копіювання складу...",
        "transferStepCategories": "Копіювання категорій...",
        "transferStepServices": "Копіювання послуг...",
        "transferStepMaterials": "Копіювання матеріалів...",
        "transferStepDone": "Завершення...",
        "transferDone": "Імпорт завершено",
        "transferNotFound": "Код не знайдено або термін минув",
        "transferNoData": "Нічого копіювати — у цього майстра немає послуг або товарів",
        "transferResultServices": "Послуги: +{{added}} нових, {{replaced}} замінено, {{skipped}} пропущено",
        "transferResultInventory": "Склад: +{{added}} нових, {{replaced}} замінено, {{skipped}} пропущено",
        "transferResultMaterials": "Матеріали до послуг: {{added}}"
    },
    "kaa": {
        "transfer": "Maǵlıwmattı ótkazıw",
        "transferShare": "Maǵlıwmatlardı bólisinw",
        "transferShareDesc": "Kod jaratiń — basqa sheber sizin xizmetleriñiz hám omboríñızdı nusxalay aladı",
        "transferShareStats": "Qoljetimli: {{services}} xizm., {{inventory}} tovar",
        "transferCreateCode": "Kod jaratıw",
        "transferCreating": "Jaratılıwda...",
        "transferActiveCode": "Aktiv kod",
        "transferExpires": "{{time}} da merzimi tamam boladı",
        "transferRevoke": "Bekar qılıw",
        "transferRevoking": "Bekar qılınıwda...",
        "transferCodeCopied": "Kod nusxalandı",
        "transferImport": "Kod boyınsha import",
        "transferImportDesc": "Xizmetler hám ombordı nusxalaw ushın basqa sheberiñ kodın kirisiń",
        "transferTokenPlaceholder": "Kodtı kirisiń (12 belgi)",
        "transferCheck": "Tekserw",
        "transferChecking": "Tekseriliwde...",
        "transferFound": "Import ushın tabıldı",
        "transferServices": "Xizmetler",
        "transferInventory": "Ombor",
        "transferStrategy": "Atlar sáykes kelgende",
        "transferStrategySkip": "Tek jańaların qosıw",
        "transferStrategyReplace": "Sáykeslerin almasturıw",
        "transferImportBtn": "Import qılıw",
        "transferImporting": "Importlanıwda...",
        "transferStepInventory": "Ombor nusxalanıwda...",
        "transferStepCategories": "Kategoriyalar nusxalanıwda...",
        "transferStepServices": "Xizmetler nusxalanıwda...",
        "transferStepMaterials": "Materiallar nusxalanıwda...",
        "transferStepDone": "Ayaqlanıwda...",
        "transferDone": "Import ayaqlandı",
        "transferNotFound": "Kod tabılmadı yáki merzimi ótken",
        "transferNoData": "Nusxalaydıǵan zat joq — bul sheberde xizmetler yáki tovarlar joq",
        "transferResultServices": "Xizmetler: +{{added}} jańa, {{replaced}} almastırıldı, {{skipped}} ótkerildi",
        "transferResultInventory": "Ombor: +{{added}} jańa, {{replaced}} almastırıldı, {{skipped}} ótkerildi",
        "transferResultMaterials": "Xizmetlerge materiallar: {{added}}"
    }
}

langs = list(BILLING.keys())

for lang in langs:
    path = f'public/locales/{lang}/translation.json'
    with open(path, 'r', encoding='utf-8') as f:
        loc = json.load(f)

    # Overwrite billing section
    loc['billing'] = BILLING[lang]

    # Overwrite profile transfer keys
    if 'profile' not in loc or not isinstance(loc['profile'], dict):
        loc['profile'] = {}
    for key, value in TRANSFER[lang].items():
        loc['profile'][key] = value

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(loc, f, ensure_ascii=False, indent=2)

    print(f'{lang}: billing ({len(BILLING[lang])} keys) + transfer ({len(TRANSFER[lang])} keys) updated')
