import json

PROMO = {
    "ru": {
        "subtitle": "Создавайте скидочные коды для клиентов",
        "create": "Создать",
        "newTitle": "Новый промокод",
        "validationError": "Заполните код и сумму скидки",
        "created": "Промокод создан",
        "createError": "Не удалось создать промокод",
        "statTotal": "Всего кодов",
        "statActive": "Активных",
        "statUses": "Использований",
        "statExpired": "Истёкших",
        "code": "Код",
        "random": "Случайный",
        "discountType": "Тип скидки",
        "discountPercent": "Процент %",
        "discountFixed": "Фиксированная",
        "discountValue": "Размер скидки",
        "maxUses": "Макс. использований",
        "validFrom": "Действует с",
        "validUntil": "Действует до",
        "description": "Описание (необязательно)",
        "descriptionPlaceholder": "Летняя акция",
        "createBtn": "Создать промокод",
        "empty": "Промокодов нет",
        "emptyHint": "Создайте первый промокод, чтобы привлечь клиентов",
        "statusExpired": "Истёк",
        "statusExhausted": "Исчерпан",
        "statusActive": "Активен",
        "statusInactive": "Выкл",
        "discount": "Скидка",
        "usageCount": "Использований: {{used}} / {{max}}",
        "usageTotal": "Использован {{count}} раз",
        "until": "До {{date}}"
    },
    "en": {
        "subtitle": "Create discount codes for clients",
        "create": "Create",
        "newTitle": "New promo code",
        "validationError": "Fill in the code and discount amount",
        "created": "Promo code created",
        "createError": "Failed to create promo code",
        "statTotal": "Total codes",
        "statActive": "Active",
        "statUses": "Uses",
        "statExpired": "Expired",
        "code": "Code",
        "random": "Random",
        "discountType": "Discount type",
        "discountPercent": "Percent %",
        "discountFixed": "Fixed",
        "discountValue": "Discount amount",
        "maxUses": "Max uses",
        "validFrom": "Valid from",
        "validUntil": "Valid until",
        "description": "Description (optional)",
        "descriptionPlaceholder": "Summer sale",
        "createBtn": "Create promo code",
        "empty": "No promo codes",
        "emptyHint": "Create your first promo code to attract clients",
        "statusExpired": "Expired",
        "statusExhausted": "Exhausted",
        "statusActive": "Active",
        "statusInactive": "Off",
        "discount": "Discount",
        "usageCount": "Uses: {{used}} / {{max}}",
        "usageTotal": "Used {{count}} times",
        "until": "Until {{date}}"
    },
    "uz": {
        "subtitle": "Mijozlar uchun chegirma kodlari yarating",
        "create": "Yaratish",
        "newTitle": "Yangi promokod",
        "validationError": "Kod va chegirma miqdorini to'ldiring",
        "created": "Promokod yaratildi",
        "createError": "Promokod yaratib bo'lmadi",
        "statTotal": "Jami kodlar",
        "statActive": "Faol",
        "statUses": "Foydalanish",
        "statExpired": "Muddati o'tgan",
        "code": "Kod",
        "random": "Tasodifiy",
        "discountType": "Chegirma turi",
        "discountPercent": "Foiz %",
        "discountFixed": "Qat'iy",
        "discountValue": "Chegirma miqdori",
        "maxUses": "Maks. foydalanish",
        "validFrom": "Amal qilish boshlanishi",
        "validUntil": "Amal qilish tugashi",
        "description": "Tavsif (ixtiyoriy)",
        "descriptionPlaceholder": "Yozgi aksiya",
        "createBtn": "Promokod yaratish",
        "empty": "Promokodlar yo'q",
        "emptyHint": "Mijozlarni jalb qilish uchun birinchi promokodni yarating",
        "statusExpired": "Muddati o'tdi",
        "statusExhausted": "Tugagan",
        "statusActive": "Faol",
        "statusInactive": "O'chirilgan",
        "discount": "Chegirma",
        "usageCount": "Foydalanish: {{used}} / {{max}}",
        "usageTotal": "{{count}} marta ishlatilgan",
        "until": "{{date}} gacha"
    },
    "kz": {
        "subtitle": "Клиенттер үшін жеңілдік кодтарын жасаңыз",
        "create": "Жасау",
        "newTitle": "Жаңа промокод",
        "validationError": "Код мен жеңілдік сомасын толтырыңыз",
        "created": "Промокод жасалды",
        "createError": "Промокод жасалмады",
        "statTotal": "Барлық кодтар",
        "statActive": "Белсенді",
        "statUses": "Қолданылуы",
        "statExpired": "Мерзімі өткен",
        "code": "Код",
        "random": "Кездейсоқ",
        "discountType": "Жеңілдік түрі",
        "discountPercent": "Пайыз %",
        "discountFixed": "Бекітілген",
        "discountValue": "Жеңілдік мөлшері",
        "maxUses": "Макс. қолдану",
        "validFrom": "Жарамды бастап",
        "validUntil": "Жарамды дейін",
        "description": "Сипаттама (міндетті емес)",
        "descriptionPlaceholder": "Жазғы акция",
        "createBtn": "Промокод жасау",
        "empty": "Промокодтар жоқ",
        "emptyHint": "Клиенттерді тарту үшін алғашқы промокодты жасаңыз",
        "statusExpired": "Мерзімі өтті",
        "statusExhausted": "Таусылды",
        "statusActive": "Белсенді",
        "statusInactive": "Өшірілген",
        "discount": "Жеңілдік",
        "usageCount": "Қолдану: {{used}} / {{max}}",
        "usageTotal": "{{count}} рет қолданылды",
        "until": "{{date}} дейін"
    },
    "ky": {
        "subtitle": "Кардарлар үчүн арзандатуу кодторун жасаңыз",
        "create": "Жасоо",
        "newTitle": "Жаңы промокод",
        "validationError": "Код менен арзандатуу суммасын толтуруңуз",
        "created": "Промокод жасалды",
        "createError": "Промокод жасалган жок",
        "statTotal": "Бардык кодтор",
        "statActive": "Активдүү",
        "statUses": "Колдонуу",
        "statExpired": "Мөөнөтү өткөн",
        "code": "Код",
        "random": "Туш келди",
        "discountType": "Арзандатуу түрү",
        "discountPercent": "Пайыз %",
        "discountFixed": "Бекитилген",
        "discountValue": "Арзандатуу өлчөмү",
        "maxUses": "Макс. колдонуу",
        "validFrom": "Жарактуу баштап",
        "validUntil": "Жарактуу чейин",
        "description": "Сүрөттөмө (милдеттүү эмес)",
        "descriptionPlaceholder": "Жайкы акция",
        "createBtn": "Промокод жасоо",
        "empty": "Промокодтор жок",
        "emptyHint": "Кардарларды тартуу үчүн биринчи промокодду жасаңыз",
        "statusExpired": "Мөөнөтү өттү",
        "statusExhausted": "Бүттү",
        "statusActive": "Активдүү",
        "statusInactive": "Өчүрүлгөн",
        "discount": "Арзандатуу",
        "usageCount": "Колдонуу: {{used}} / {{max}}",
        "usageTotal": "{{count}} жолу колдонулду",
        "until": "{{date}} чейин"
    },
    "tg": {
        "subtitle": "Барои муштариён кодҳои тахфиф созед",
        "create": "Сохтан",
        "newTitle": "Промокоди нав",
        "validationError": "Код ва маблағи тахфифро пур кунед",
        "created": "Промокод сохта шуд",
        "createError": "Промокод сохта нашуд",
        "statTotal": "Ҳамаи кодҳо",
        "statActive": "Фаъол",
        "statUses": "Истифода",
        "statExpired": "Муддат гузашт",
        "code": "Код",
        "random": "Тасодуфӣ",
        "discountType": "Навъи тахфиф",
        "discountPercent": "Фоиз %",
        "discountFixed": "Доимӣ",
        "discountValue": "Андозаи тахфиф",
        "maxUses": "Макс. истифода",
        "validFrom": "Аз санаи",
        "validUntil": "То санаи",
        "description": "Тавсиф (ихтиёрӣ)",
        "descriptionPlaceholder": "Акцияи тобистона",
        "createBtn": "Промокод сохтан",
        "empty": "Промокодҳо нест",
        "emptyHint": "Барои ҷалби муштариён промокоди аввалинро созед",
        "statusExpired": "Муддат гузашт",
        "statusExhausted": "Тамом шуд",
        "statusActive": "Фаъол",
        "statusInactive": "Хомӯш",
        "discount": "Тахфиф",
        "usageCount": "Истифода: {{used}} / {{max}}",
        "usageTotal": "{{count}} маротиба истифода шуд",
        "until": "То {{date}}"
    },
    "by": {
        "subtitle": "Стварайце зніжачныя коды для кліентаў",
        "create": "Стварыць",
        "newTitle": "Новы прамакод",
        "validationError": "Запоўніце код і суму зніжкі",
        "created": "Прамакод створаны",
        "createError": "Не ўдалося стварыць прамакод",
        "statTotal": "Усяго кодаў",
        "statActive": "Актыўных",
        "statUses": "Выкарыстанняў",
        "statExpired": "Прасрочаных",
        "code": "Код",
        "random": "Выпадковы",
        "discountType": "Тып зніжкі",
        "discountPercent": "Адсоткі %",
        "discountFixed": "Фіксаваная",
        "discountValue": "Памер зніжкі",
        "maxUses": "Макс. выкарыстанняў",
        "validFrom": "Дзейнічае з",
        "validUntil": "Дзейнічае да",
        "description": "Апісанне (неабавязкова)",
        "descriptionPlaceholder": "Летняя акцыя",
        "createBtn": "Стварыць прамакод",
        "empty": "Прамакодаў няма",
        "emptyHint": "Стварыце першы прамакод, каб прыцягнуць кліентаў",
        "statusExpired": "Прасрочаны",
        "statusExhausted": "Вычарпаны",
        "statusActive": "Актыўны",
        "statusInactive": "Адключаны",
        "discount": "Зніжка",
        "usageCount": "Выкарыстанняў: {{used}} / {{max}}",
        "usageTotal": "Выкарыстаны {{count}} разоў",
        "until": "Да {{date}}"
    },
    "uk": {
        "subtitle": "Створюйте знижкові коди для клієнтів",
        "create": "Створити",
        "newTitle": "Новий промокод",
        "validationError": "Заповніть код і суму знижки",
        "created": "Промокод створено",
        "createError": "Не вдалося створити промокод",
        "statTotal": "Всього кодів",
        "statActive": "Активних",
        "statUses": "Використань",
        "statExpired": "Прострочених",
        "code": "Код",
        "random": "Випадковий",
        "discountType": "Тип знижки",
        "discountPercent": "Відсоток %",
        "discountFixed": "Фіксована",
        "discountValue": "Розмір знижки",
        "maxUses": "Макс. використань",
        "validFrom": "Діє від",
        "validUntil": "Діє до",
        "description": "Опис (необов'язково)",
        "descriptionPlaceholder": "Літній розпродаж",
        "createBtn": "Створити промокод",
        "empty": "Промокодів немає",
        "emptyHint": "Створіть перший промокод, щоб залучити клієнтів",
        "statusExpired": "Прострочений",
        "statusExhausted": "Вичерпаний",
        "statusActive": "Активний",
        "statusInactive": "Вимкнено",
        "discount": "Знижка",
        "usageCount": "Використань: {{used}} / {{max}}",
        "usageTotal": "Використано {{count}} разів",
        "until": "До {{date}}"
    },
    "kaa": {
        "subtitle": "Mijozlar ushın chegirma kodları jaratiń",
        "create": "Jaratıw",
        "newTitle": "Jańa promokod",
        "validationError": "Kod hám chegirma muqdarın toltırıń",
        "created": "Promokod jaratıldı",
        "createError": "Promokod jaratıp bolmadı",
        "statTotal": "Barlıq kodlar",
        "statActive": "Aktiv",
        "statUses": "Paydalanıw",
        "statExpired": "Merzimi ótken",
        "code": "Kod",
        "random": "Tasadıypı",
        "discountType": "Chegirma túri",
        "discountPercent": "Payız %",
        "discountFixed": "Turaqli",
        "discountValue": "Chegirma muqdarı",
        "maxUses": "Maks. paydalanıw",
        "validFrom": "Járamlı baslapan",
        "validUntil": "Járamlı sheklem",
        "description": "Sıpatlama (ixtiyariy)",
        "descriptionPlaceholder": "Jazǵı aksiya",
        "createBtn": "Promokod jaratıw",
        "empty": "Promokodlar joq",
        "emptyHint": "Mijozlardı tartıw ushın birinji promokodtı jaratiń",
        "statusExpired": "Merzimi ótken",
        "statusExhausted": "Tamam boldı",
        "statusActive": "Aktiv",
        "statusInactive": "Ósiriw",
        "discount": "Chegirma",
        "usageCount": "Paydalanıw: {{used}} / {{max}}",
        "usageTotal": "{{count}} marte paydalanıldı",
        "until": "{{date}} shekem"
    }
}

langs = list(PROMO.keys())

for lang in langs:
    path = f'public/locales/{lang}/translation.json'
    with open(path, 'r', encoding='utf-8') as f:
        loc = json.load(f)

    # Always overwrite the promo section completely
    loc['promo'] = PROMO[lang]

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(loc, f, ensure_ascii=False, indent=2)
    print(f'{lang}: promo section updated ({len(PROMO[lang])} keys)')
