import json

MODEL_DESC_RU = {
    "fastCheapRec": "Быстро, дешево · рекомендуется",
    "fast": "Быстро, лёгкая",
    "balanced": "Сбалансирована",
    "smart": "Умная, мощная",
    "smartestExpensive": "Самая умная · дороже",
    "smartVersatile": "Умная, универсальная",
    "powerful": "Мощная, быстрая",
    "logicReasoning": "Логика и рассуждения",
    "fastRec": "Быстро · рекомендуется",
    "economical": "Экономична, быстрая",
    "smartBigContext": "Умная, большой контекст",
    "smartest": "Самая умная",
    "chatCheapRec": "Чат, дешево · рекомендуется",
    "complexReasoning": "Сложные рассуждения",
    "balancedRec": "Сбалансирована · рекомендуется",
    "fastCheap": "Быстро, дешево",
    "opensourcePowerful": "Open-source, мощная"
}
MODEL_DESC_EN = {
    "fastCheapRec": "Fast, cheap · recommended",
    "fast": "Fast, lightweight",
    "balanced": "Balanced",
    "smart": "Smart, powerful",
    "smartestExpensive": "Smartest · pricier",
    "smartVersatile": "Smart, versatile",
    "powerful": "Powerful, fast",
    "logicReasoning": "Logic & reasoning",
    "fastRec": "Fast · recommended",
    "economical": "Economical, fast",
    "smartBigContext": "Smart, large context",
    "smartest": "Smartest",
    "chatCheapRec": "Chat, cheap · recommended",
    "complexReasoning": "Complex reasoning",
    "balancedRec": "Balanced · recommended",
    "fastCheap": "Fast, cheap",
    "opensourcePowerful": "Open-source, powerful"
}
MODEL_DESC_UZ = {
    "fastCheapRec": "Tez, arzon · tavsiya etiladi",
    "fast": "Tez, engil",
    "balanced": "Muvozanatli",
    "smart": "Aqlli, kuchli",
    "smartestExpensive": "Eng aqlli · qimmatroq",
    "smartVersatile": "Aqlli, universal",
    "powerful": "Kuchli, tez",
    "logicReasoning": "Mantiq va mulohaza",
    "fastRec": "Tez · tavsiya etiladi",
    "economical": "Tejamkor, tez",
    "smartBigContext": "Aqlli, katta kontekst",
    "smartest": "Eng aqlli",
    "chatCheapRec": "Chat, arzon · tavsiya etiladi",
    "complexReasoning": "Murakkab mulohaza",
    "balancedRec": "Muvozanatli · tavsiya etiladi",
    "fastCheap": "Tez, arzon",
    "opensourcePowerful": "Open-source, kuchli"
}
MODEL_DESC_KZ = {
    "fastCheapRec": "Жылдам, арзан · ұсынылады",
    "fast": "Жылдам, жеңіл",
    "balanced": "Теңгерімді",
    "smart": "Ақылды, қуатты",
    "smartestExpensive": "Ең ақылды · қымбатырақ",
    "smartVersatile": "Ақылды, әмбебап",
    "powerful": "Қуатты, жылдам",
    "logicReasoning": "Логика және пайымдау",
    "fastRec": "Жылдам · ұсынылады",
    "economical": "Үнемді, жылдам",
    "smartBigContext": "Ақылды, үлкен контекст",
    "smartest": "Ең ақылды",
    "chatCheapRec": "Чат, арзан · ұсынылады",
    "complexReasoning": "Күрделі пайымдау",
    "balancedRec": "Теңгерімді · ұсынылады",
    "fastCheap": "Жылдам, арзан",
    "opensourcePowerful": "Open-source, қуатты"
}
MODEL_DESC_KY = {
    "fastCheapRec": "Тез, арзан · сунушталат",
    "fast": "Тез, жеңил",
    "balanced": "Тең салмактуу",
    "smart": "Акылдуу, күчтүү",
    "smartestExpensive": "Эң акылдуу · кымбатыраак",
    "smartVersatile": "Акылдуу, универсал",
    "powerful": "Күчтүү, тез",
    "logicReasoning": "Логика жана ой жүгүртүү",
    "fastRec": "Тез · сунушталат",
    "economical": "Үнөмдүү, тез",
    "smartBigContext": "Акылдуу, чоң контекст",
    "smartest": "Эң акылдуу",
    "chatCheapRec": "Чат, арзан · сунушталат",
    "complexReasoning": "Татаал ой жүгүртүү",
    "balancedRec": "Тең салмактуу · сунушталат",
    "fastCheap": "Тез, арзан",
    "opensourcePowerful": "Open-source, күчтүү"
}
MODEL_DESC_TG = {
    "fastCheapRec": "Тез, арзон · тавсия дода мешавад",
    "fast": "Тез, сабук",
    "balanced": "Мутавозин",
    "smart": "Ақлманд, қавӣ",
    "smartestExpensive": "Аз ҳама ақлманд · гаронтар",
    "smartVersatile": "Ақлманд, универсалӣ",
    "powerful": "Қавӣ, тез",
    "logicReasoning": "Мантиқ ва тафаккур",
    "fastRec": "Тез · тавсия дода мешавад",
    "economical": "Сарфакор, тез",
    "smartBigContext": "Ақлманд, контексти калон",
    "smartest": "Аз ҳама ақлманд",
    "chatCheapRec": "Чат, арзон · тавсия дода мешавад",
    "complexReasoning": "Тафаккури мураккаб",
    "balancedRec": "Мутавозин · тавсия дода мешавад",
    "fastCheap": "Тез, арзон",
    "opensourcePowerful": "Open-source, қавӣ"
}
MODEL_DESC_BY = {
    "fastCheapRec": "Хутка, танна · рэкамендуецца",
    "fast": "Хутка, лёгкая",
    "balanced": "Збалансаваная",
    "smart": "Разумная, магутная",
    "smartestExpensive": "Самая разумная · даражэй",
    "smartVersatile": "Разумная, універсальная",
    "powerful": "Магутная, хуткая",
    "logicReasoning": "Логіка і разважанні",
    "fastRec": "Хутка · рэкамендуецца",
    "economical": "Эканомная, хуткая",
    "smartBigContext": "Разумная, вялікі кантэкст",
    "smartest": "Самая разумная",
    "chatCheapRec": "Чат, танна · рэкамендуецца",
    "complexReasoning": "Складаныя разважанні",
    "balancedRec": "Збалансаваная · рэкамендуецца",
    "fastCheap": "Хутка, танна",
    "opensourcePowerful": "Open-source, магутная"
}
MODEL_DESC_UK = {
    "fastCheapRec": "Швидко, дешево · рекомендується",
    "fast": "Швидко, легка",
    "balanced": "Збалансована",
    "smart": "Розумна, потужна",
    "smartestExpensive": "Найрозумніша · дорожче",
    "smartVersatile": "Розумна, універсальна",
    "powerful": "Потужна, швидка",
    "logicReasoning": "Логіка та міркування",
    "fastRec": "Швидко · рекомендується",
    "economical": "Економна, швидка",
    "smartBigContext": "Розумна, великий контекст",
    "smartest": "Найрозумніша",
    "chatCheapRec": "Чат, дешево · рекомендується",
    "complexReasoning": "Складні міркування",
    "balancedRec": "Збалансована · рекомендується",
    "fastCheap": "Швидко, дешево",
    "opensourcePowerful": "Open-source, потужна"
}
MODEL_DESC_KAA = {
    "fastCheapRec": "Tez, arzon · usınıladı",
    "fast": "Tez, jeńil",
    "balanced": "Teń salmaqlı",
    "smart": "Aqıllı, qúwatlı",
    "smartestExpensive": "Eń aqıllı · qımbatıraq",
    "smartVersatile": "Aqıllı, universal",
    "powerful": "Qúwatlı, tez",
    "logicReasoning": "Logika hám oylaw",
    "fastRec": "Tez · usınıladı",
    "economical": "Tejemli, tez",
    "smartBigContext": "Aqıllı, úlken kontekst",
    "smartest": "Eń aqıllı",
    "chatCheapRec": "Chat, arzon · usınıladı",
    "complexReasoning": "Quramalı oylaw",
    "balancedRec": "Teń salmaqlı · usınıladı",
    "fastCheap": "Tez, arzon",
    "opensourcePowerful": "Open-source, qúwatlı"
}

ADMIN = {
    "ru": {
        "pageTitle": "Панель администратора",
        "pageDesc": "Управление функциями, пользователями и справочниками платформы",
        "tabFeatures": "Функции",
        "tabUsers": "Пользователи",
        "tabCatalogs": "Справочники",
        "tabAppearance": "Оформление",
        "tabBilling": "Биллинг",
        "tabEmail": "Email",
        "tabAI": "ИИ",
        "specialtiesTitle": "Справочник специальностей",
        "specialtiesDesc": "Управление видами деятельности и специальностями для мастеров",
        "openSpecialties": "Открыть справочник",
        "tabBrowse": "Справочник",
        "tabImport": "Импорт",
        "newTypePlaceholder": "Добавить вид деятельности...",
        "newSpecPlaceholder": "Добавить специальность...",
        "addSpec": "Добавить специальность",
        "noTypes": "Видов деятельности пока нет. Добавьте первый.",
        "typeCreated": "Вид деятельности добавлен",
        "typeDeleted": "Вид деятельности удалён",
        "typeDeleteConfirm": "Удалить вид деятельности и все его специальности?",
        "specCreated": "Специальность добавлена",
        "specDeleted": "Специальность удалена",
        "specDeleteConfirm": "Удалить специальность?",
        "seedTitle": "Загрузить встроенный справочник",
        "seedDesc": "{{count}} специальностей по 9 видам деятельности",
        "loadSeed": "Загрузить справочник",
        "orImport": "или импортируйте свой список",
        "importFormat": "Формат данных",
        "uploadFile": "Загрузить файл",
        "pasteArea": "Вставить данные",
        "previewBtn": "Предпросмотр",
        "previewTitle": "Найдено записей: {{count}}",
        "importBtn": "Импортировать {{count}} записей",
        "importSuccess": "Импортировано: {{count}} новых записей",
        "importParseError": "Ошибка разбора данных. Проверьте формат.",
        "importDefaultType": "Общее",
        "usersTitle": "Пользователи",
        "usersDesc": "Управление ролями пользователей платформы",
        "openUsers": "Управление пользователями",
        "usersEmpty": "Пользователей пока нет",
        "makeAdmin": "Сделать администратором",
        "makeAdminSuccess": "Роль администратора назначена",
        "removeAdmin": "Убрать роль администратора",
        "removeAdminSuccess": "Роль администратора снята",
        "roleAdmin": "Администратор",
        "roleMaster": "Мастер",
        "youLabel": "вы",
        "cannotSelf": "Нельзя изменить свою роль",
        "searchUsers": "Поиск по имени или email...",
        "usersNotFound": "Пользователи не найдены",
        "disableUser": "Отключить пользователя",
        "enableUser": "Включить пользователя",
        "userDisabled": "Пользователь отключён",
        "userEnabled": "Пользователь включён",
        "disabled": "Заблокирован",
        "active": "Активен",
        "userIsDisabled": "Доступ заблокирован — пользователь не может войти",
        "exportCSV": "Экспорт в CSV",
        "exportDone": "Экспорт завершён",
        "statsTotal": "Всего",
        "statsNewMonth": "Новых в месяце",
        "statsPaid": "Платных",
        "statsDisabled": "Отключённых",
        "colUser": "Пользователь",
        "colPlan": "План",
        "colAdmin": "Админ",
        "colStatus": "Статус",
        "userDeleted": "Пользователь удалён",
        "deleteError": "Ошибка удаления",
        "deletedCount": "Удалено {{count}} пользователей",
        "deleteFailedCount": "Ошибка при удалении {{count}} пользователей",
        "selectedCount": "Выбрано: {{count}}",
        "deselect": "Снять",
        "deleteSelected": "Удалить ({{count}})",
        "selectAll": "Выбрать всех",
        "selectUser": "Выбрать {{name}}",
        "cannotDeleteAdmin": "Администратор не может быть удалён",
        "deleteUserAction": "Удалить пользователя",
        "cannotRemoveAdmin": "Нельзя снять роль администратора",
        "csvName": "Имя",
        "csvEmail": "Email",
        "csvPlan": "План",
        "csvAdmin": "Админ",
        "csvDisabled": "Заблокирован",
        "csvDate": "Дата регистрации",
        "csvYes": "да",
        "csvNo": "нет",
        "bulkDeleteTitle": "Удалить {{count}} пользователей?",
        "bulkDeleteDesc": "Все {{count}} выбранных пользователей будут удалены навсегда.",
        "deleteUserTitle": "Удалить пользователя?",
        "deleteUserDesc": "Это действие необратимо.",
        "deleteIrreversible": "Все данные будут удалены навсегда.",
        "deleteUserDetails": "Пользователь: {{name}} ({{email}})",
        "deleting": "Удаление...",
        "featuresDesc": "Включайте и отключайте функции платформы, задавайте минимальный план доступа",
        "searchFeature": "Поиск функции...",
        "featureEnabled": "Функция включена",
        "featureDisabled": "Функция отключена",
        "featureEnableHint": "Включить функцию",
        "featureDisableHint": "Отключить функцию",
        "logoHint": "PNG, JPG, SVG · до 5 МБ",
        "fontSize": "Размер шрифта",
        "fontSizeDesc": "Влияет на весь интерфейс, включая Telegram Mini App",
        "fontSmall": "Маленький",
        "fontMedium": "Средний",
        "fontLarge": "Крупный",
        "catalogsDesc": "Управление глобальными справочниками платформы, доступными всем пользователям",
        "globalServicesTitle": "Справочник услуг",
        "globalServicesDesc": "Глобальный список услуг для быстрого добавления в профиль мастера",
        "openGlobalServices": "Открыть справочник услуг",
        "globalProductsTitle": "Справочник товаров",
        "globalProductsDesc": "Глобальный список товаров и материалов для склада",
        "openGlobalProducts": "Открыть справочник товаров",
        "comingSoon": "Скоро",
        "registeredAt": "Зарегистрирован",
        "limitMetric": "Метрика",
        "limitHint": "Отключите строку, если этот лимит не нужен.",
        "emailDesc": "Настройки SMTP-сервера и email-уведомлений",
        "emailGlobalEnabled": "Email-уведомления включены",
        "emailGlobalEnabledDesc": "Разрешить отправку писем мастерам и клиентам",
        "smtpTitle": "SMTP сервер",
        "smtpHint": "Рекомендуется: Resend — host smtp.resend.com, port 587, user resend, password = API key с resend.com",
        "smtpHost": "Host",
        "smtpPort": "Порт",
        "smtpUser": "Пользователь",
        "smtpPass": "Пароль / API ключ",
        "fromAddress": "Email отправителя",
        "fromName": "Имя отправителя",
        "smtpSaved": "Настройки SMTP сохранены",
        "notifyPerMasterTitle": "Уведомления — по мастерам",
        "notifyPerMasterDesc": "Каждый мастер включает email-уведомления в Настройках → Уведомления и может установить свой шаблон",
        "ai": {
            "desc": "Настройки ИИ-помощника. Используется для генерации текста профиля, анализа клиентов и ответов Telegram-бота.",
            "enabled": "ИИ включён",
            "enabledDesc": "Разрешить использование функций ИИ",
            "provider": "Провайдер",
            "customProvider": "Custom (совместима с OpenAI)",
            "apiKey": "API ключ",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Получить ключ на",
            "baseUrlHint": "URL API (для провайдеров совместимых с OpenAI)",
            "model": "Модель",
            "modelPlaceholder": "Введите название модели",
            "maxTokens": "Макс. токенов",
            "tokensRange": "256 до 8192",
            "tokensHint": "Ограничивает длину ответов ИИ",
            "save": "Сохранить",
            "saved": "Настройки ИИ сохранены",
            "status": "Статус",
            "keySet": "ключ установлен",
            "keyNotSet": "ключ не установлен",
            "active": "Активна",
            "modelLabel": "Модель:",
            "tokensLabel": "Токены:",
            "inactive": "Неактивна",
            "usedBy": "Используется для:",
            "featureBio": "Генерация текста профиля",
            "featureAnalysis": "Анализ базы клиентов",
            "featureBot": "Ответы Telegram-бота",
            "modelDesc": MODEL_DESC_RU
        }
    },
    "en": {
        "pageTitle": "Admin Panel",
        "pageDesc": "Manage platform features, users and catalogs",
        "tabFeatures": "Features",
        "tabUsers": "Users",
        "tabCatalogs": "Catalogs",
        "tabAppearance": "Appearance",
        "tabBilling": "Billing",
        "tabEmail": "Email",
        "tabAI": "AI",
        "specialtiesTitle": "Specialties Directory",
        "specialtiesDesc": "Manage activity types and specialties for masters",
        "openSpecialties": "Open directory",
        "tabBrowse": "Directory",
        "tabImport": "Import",
        "newTypePlaceholder": "Add activity type...",
        "newSpecPlaceholder": "Add specialty...",
        "addSpec": "Add specialty",
        "noTypes": "No activity types yet. Add the first one.",
        "typeCreated": "Activity type added",
        "typeDeleted": "Activity type deleted",
        "typeDeleteConfirm": "Delete activity type and all its specialties?",
        "specCreated": "Specialty added",
        "specDeleted": "Specialty deleted",
        "specDeleteConfirm": "Delete specialty?",
        "seedTitle": "Load built-in directory",
        "seedDesc": "{{count}} specialties across 9 activity types",
        "loadSeed": "Load directory",
        "orImport": "or import your own list",
        "importFormat": "Data format",
        "uploadFile": "Upload file",
        "pasteArea": "Paste data",
        "previewBtn": "Preview",
        "previewTitle": "Records found: {{count}}",
        "importBtn": "Import {{count}} records",
        "importSuccess": "Imported: {{count}} new records",
        "importParseError": "Parse error. Check the format.",
        "importDefaultType": "General",
        "usersTitle": "Users",
        "usersDesc": "Manage platform user roles",
        "openUsers": "Manage Users",
        "usersEmpty": "No users yet",
        "makeAdmin": "Make Administrator",
        "makeAdminSuccess": "Admin role granted",
        "removeAdmin": "Remove Admin Role",
        "removeAdminSuccess": "Admin role removed",
        "roleAdmin": "Administrator",
        "roleMaster": "Master",
        "youLabel": "you",
        "cannotSelf": "Cannot change your own role",
        "searchUsers": "Search by name or email...",
        "usersNotFound": "Users not found",
        "disableUser": "Disable user",
        "enableUser": "Enable user",
        "userDisabled": "User disabled",
        "userEnabled": "User enabled",
        "disabled": "Blocked",
        "active": "Active",
        "userIsDisabled": "Access blocked — user cannot log in",
        "exportCSV": "Export to CSV",
        "exportDone": "Export complete",
        "statsTotal": "Total",
        "statsNewMonth": "New this month",
        "statsPaid": "Paid",
        "statsDisabled": "Disabled",
        "colUser": "User",
        "colPlan": "Plan",
        "colAdmin": "Admin",
        "colStatus": "Status",
        "userDeleted": "User deleted",
        "deleteError": "Delete failed",
        "deletedCount": "Deleted {{count}} users",
        "deleteFailedCount": "Failed to delete {{count}} users",
        "selectedCount": "Selected: {{count}}",
        "deselect": "Deselect",
        "deleteSelected": "Delete ({{count}})",
        "selectAll": "Select all",
        "selectUser": "Select {{name}}",
        "cannotDeleteAdmin": "Admin cannot be deleted",
        "deleteUserAction": "Delete user",
        "cannotRemoveAdmin": "Cannot remove admin role",
        "csvName": "Name",
        "csvEmail": "Email",
        "csvPlan": "Plan",
        "csvAdmin": "Admin",
        "csvDisabled": "Disabled",
        "csvDate": "Registration date",
        "csvYes": "yes",
        "csvNo": "no",
        "bulkDeleteTitle": "Delete {{count}} users?",
        "bulkDeleteDesc": "All {{count}} selected users will be permanently deleted.",
        "deleteUserTitle": "Delete user?",
        "deleteUserDesc": "This action is irreversible.",
        "deleteIrreversible": "All data will be permanently deleted.",
        "deleteUserDetails": "User: {{name}} ({{email}})",
        "deleting": "Deleting...",
        "featuresDesc": "Enable or disable platform features and set minimum plan requirements",
        "searchFeature": "Search feature...",
        "featureEnabled": "Feature enabled",
        "featureDisabled": "Feature disabled",
        "featureEnableHint": "Enable feature",
        "featureDisableHint": "Disable feature",
        "logoHint": "PNG, JPG, SVG · up to 5 MB",
        "fontSize": "Font size",
        "fontSizeDesc": "Affects the entire interface, including Telegram Mini App",
        "fontSmall": "Small",
        "fontMedium": "Medium",
        "fontLarge": "Large",
        "catalogsDesc": "Manage global platform catalogs available to all users",
        "globalServicesTitle": "Services Catalog",
        "globalServicesDesc": "Global list of services for quick addition to master profile",
        "openGlobalServices": "Open services catalog",
        "globalProductsTitle": "Products Catalog",
        "globalProductsDesc": "Global list of products and materials for inventory",
        "openGlobalProducts": "Open products catalog",
        "comingSoon": "Coming soon",
        "registeredAt": "Registered",
        "limitMetric": "Metric",
        "limitHint": "Disable the row if this limit is not needed.",
        "emailDesc": "SMTP server and email notification settings",
        "emailGlobalEnabled": "Email notifications enabled",
        "emailGlobalEnabledDesc": "Allow sending emails to masters and clients",
        "smtpTitle": "SMTP Server",
        "smtpHint": "Recommended: Resend — host smtp.resend.com, port 587, user resend, password = API key from resend.com",
        "smtpHost": "Host",
        "smtpPort": "Port",
        "smtpUser": "Username",
        "smtpPass": "Password / API key",
        "fromAddress": "Sender email",
        "fromName": "Sender name",
        "smtpSaved": "SMTP settings saved",
        "notifyPerMasterTitle": "Notifications — per master",
        "notifyPerMasterDesc": "Each master enables email notifications in Settings → Notifications and can set a custom template",
        "ai": {
            "desc": "AI assistant settings. Used for profile text generation, client analysis and Telegram bot responses.",
            "enabled": "AI enabled",
            "enabledDesc": "Allow use of AI features",
            "provider": "Provider",
            "customProvider": "Custom (OpenAI-compatible)",
            "apiKey": "API key",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Get key at",
            "baseUrlHint": "API URL (for OpenAI-compatible providers)",
            "model": "Model",
            "modelPlaceholder": "Enter model name",
            "maxTokens": "Max tokens",
            "tokensRange": "256 to 8192",
            "tokensHint": "Limits the length of AI responses",
            "save": "Save settings",
            "saved": "AI settings saved",
            "status": "Status",
            "keySet": "key set",
            "keyNotSet": "key not set",
            "active": "Active",
            "modelLabel": "Model:",
            "tokensLabel": "Tokens:",
            "inactive": "Inactive",
            "usedBy": "Used for:",
            "featureBio": "Profile text generation",
            "featureAnalysis": "Client base analysis",
            "featureBot": "Telegram bot responses",
            "modelDesc": MODEL_DESC_EN
        }
    },
    "uz": {
        "pageTitle": "Administrator paneli",
        "pageDesc": "Platforma funksiyalari, foydalanuvchilar va ma'lumotnomalari boshqarish",
        "tabFeatures": "Funksiyalar",
        "tabUsers": "Foydalanuvchilar",
        "tabCatalogs": "Ma'lumotnomalar",
        "tabAppearance": "Ko'rinish",
        "tabBilling": "Billing",
        "tabEmail": "Email",
        "tabAI": "AI",
        "specialtiesTitle": "Mutaxassisliklar ma'lumotnomasi",
        "specialtiesDesc": "Masterlar uchun faoliyat turlari va mutaxassisliklarni boshqarish",
        "openSpecialties": "Ma'lumotnomasini ochish",
        "tabBrowse": "Ma'lumotnoma",
        "tabImport": "Import",
        "newTypePlaceholder": "Faoliyat turini qo'shish...",
        "newSpecPlaceholder": "Mutaxassislik qo'shish...",
        "addSpec": "Mutaxassislik qo'shish",
        "noTypes": "Faoliyat turlari hali yo'q. Birinchisini qo'shing.",
        "typeCreated": "Faoliyat turi qo'shildi",
        "typeDeleted": "Faoliyat turi o'chirildi",
        "typeDeleteConfirm": "Faoliyat turini va uning barcha mutaxassisliklarini o'chirish kerakmi?",
        "specCreated": "Mutaxassislik qo'shildi",
        "specDeleted": "Mutaxassislik o'chirildi",
        "specDeleteConfirm": "Mutaxassislikni o'chirish kerakmi?",
        "seedTitle": "Ichki ma'lumotnomasini yuklash",
        "seedDesc": "{{count}} ta mutaxassislik 9 ta faoliyat turi bo'yicha",
        "loadSeed": "Ma'lumotnomasini yuklash",
        "orImport": "yoki o'z ro'yxatingizni import qiling",
        "importFormat": "Ma'lumotlar formati",
        "uploadFile": "Faylni yuklash",
        "pasteArea": "Ma'lumotlarni joylashtiring",
        "previewBtn": "Ko'rib chiqish",
        "previewTitle": "Topilgan yozuvlar: {{count}}",
        "importBtn": "{{count}} ta yozuvni import qilish",
        "importSuccess": "Import qilindi: {{count}} ta yangi yozuv",
        "importParseError": "Ma'lumotlarni o'qishda xato. Formatni tekshiring.",
        "importDefaultType": "Umumiy",
        "usersTitle": "Foydalanuvchilar",
        "usersDesc": "Platforma foydalanuvchilari rollarini boshqarish",
        "openUsers": "Foydalanuvchilarni boshqarish",
        "usersEmpty": "Foydalanuvchilar hali yo'q",
        "makeAdmin": "Administrator qilish",
        "makeAdminSuccess": "Administrator roli berildi",
        "removeAdmin": "Administrator rolini olish",
        "removeAdminSuccess": "Administrator roli olindi",
        "roleAdmin": "Administrator",
        "roleMaster": "Usta",
        "youLabel": "siz",
        "cannotSelf": "O'z rolingizni o'zgartirib bo'lmaydi",
        "searchUsers": "Ism yoki email bo'yicha qidirish...",
        "usersNotFound": "Foydalanuvchilar topilmadi",
        "disableUser": "Foydalanuvchini bloklash",
        "enableUser": "Foydalanuvchini yoqish",
        "userDisabled": "Foydalanuvchi bloklandi",
        "userEnabled": "Foydalanuvchi yoqildi",
        "disabled": "Bloklangan",
        "active": "Faol",
        "userIsDisabled": "Kirish bloklangan — foydalanuvchi kira olmaydi",
        "exportCSV": "CSV ga eksport",
        "exportDone": "Eksport yakunlandi",
        "statsTotal": "Jami",
        "statsNewMonth": "Oyda yangi",
        "statsPaid": "Pullik",
        "statsDisabled": "Bloklangan",
        "colUser": "Foydalanuvchi",
        "colPlan": "Tarif",
        "colAdmin": "Admin",
        "colStatus": "Holat",
        "userDeleted": "Foydalanuvchi o'chirildi",
        "deleteError": "O'chirishda xato",
        "deletedCount": "{{count}} ta foydalanuvchi o'chirildi",
        "deleteFailedCount": "{{count}} ta foydalanuvchini o'chirishda xato",
        "selectedCount": "Tanlangan: {{count}}",
        "deselect": "Bekor qilish",
        "deleteSelected": "O'chirish ({{count}})",
        "selectAll": "Barchasini tanlash",
        "selectUser": "{{name}} tanlash",
        "cannotDeleteAdmin": "Administratorni o'chirib bo'lmaydi",
        "deleteUserAction": "Foydalanuvchini o'chirish",
        "cannotRemoveAdmin": "Administrator rolini olib bo'lmaydi",
        "csvName": "Ism",
        "csvEmail": "Email",
        "csvPlan": "Tarif",
        "csvAdmin": "Admin",
        "csvDisabled": "Bloklangan",
        "csvDate": "Ro'yxatdan o'tgan sana",
        "csvYes": "ha",
        "csvNo": "yo'q",
        "bulkDeleteTitle": "{{count}} ta foydalanuvchini o'chirish kerakmi?",
        "bulkDeleteDesc": "Barcha {{count}} ta tanlangan foydalanuvchi butunlay o'chiriladi.",
        "deleteUserTitle": "Foydalanuvchini o'chirish kerakmi?",
        "deleteUserDesc": "Bu amal qaytarib bo'lmaydi.",
        "deleteIrreversible": "Barcha ma'lumotlar butunlay o'chiriladi.",
        "deleteUserDetails": "Foydalanuvchi: {{name}} ({{email}})",
        "deleting": "O'chirilmoqda...",
        "featuresDesc": "Platforma funksiyalarini yoqing va o'chiring, minimal kirish rejasini belgilang",
        "searchFeature": "Funksiyani qidirish...",
        "featureEnabled": "Funksiya yoqildi",
        "featureDisabled": "Funksiya o'chirildi",
        "featureEnableHint": "Funksiyani yoqish",
        "featureDisableHint": "Funksiyani o'chirish",
        "logoHint": "PNG, JPG, SVG · 5 MB gacha",
        "fontSize": "Shrift o'lchami",
        "fontSizeDesc": "Telegram Mini App ni ham qo'shgan holda butun interfeys",
        "fontSmall": "Kichik",
        "fontMedium": "O'rta",
        "fontLarge": "Katta",
        "catalogsDesc": "Barcha foydalanuvchilarga mavjud bo'lgan global platforma ma'lumotnomalari",
        "globalServicesTitle": "Xizmatlar ma'lumotnomasi",
        "globalServicesDesc": "Usta profiliga tez qo'shish uchun xizmatlarning global ro'yxati",
        "openGlobalServices": "Xizmatlar ma'lumotnomasini ochish",
        "globalProductsTitle": "Tovarlar ma'lumotnomasi",
        "globalProductsDesc": "Ombor uchun tovarlar va materiallarning global ro'yxati",
        "openGlobalProducts": "Tovarlar ma'lumotnomasini ochish",
        "comingSoon": "Tez orada",
        "registeredAt": "Ro'yxatdan o'tgan",
        "limitMetric": "Ko'rsatkich",
        "limitHint": "Agar bu limit kerak bo'lmasa, qatorni o'chiring.",
        "emailDesc": "SMTP-server va email-bildirishnomalar sozlamalari",
        "emailGlobalEnabled": "Email-bildirishnomalar yoqilgan",
        "emailGlobalEnabledDesc": "Ustalarga va mijozlarga xat yuborishga ruxsat berish",
        "smtpTitle": "SMTP server",
        "smtpHint": "Tavsiya etiladi: Resend — host smtp.resend.com, port 587, user resend, parol = resend.com dan API kalit",
        "smtpHost": "Host",
        "smtpPort": "Port",
        "smtpUser": "Foydalanuvchi",
        "smtpPass": "Parol / API kalit",
        "fromAddress": "Yuboruvchi email",
        "fromName": "Yuboruvchi nomi",
        "smtpSaved": "SMTP sozlamalari saqlandi",
        "notifyPerMasterTitle": "Bildirishnomalar — masterlar bo'yicha",
        "notifyPerMasterDesc": "Har bir master Sozlamalar → Bildirishnomalar da email-bildirishnomalarni yoqadi va o'z shablonini o'rnatishi mumkin",
        "ai": {
            "desc": "AI-yordamchi sozlamalari. Profil matni yaratish, mijozlarni tahlil qilish va Telegram-bot javoblari uchun ishlatiladi.",
            "enabled": "AI yoqilgan",
            "enabledDesc": "AI funksiyalaridan foydalanishga ruxsat berish",
            "provider": "Provayder",
            "customProvider": "Custom (OpenAI bilan mos)",
            "apiKey": "API kalit",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Kalitni olish",
            "baseUrlHint": "API URL (OpenAI bilan mos provayderlar uchun)",
            "model": "Model",
            "modelPlaceholder": "Model nomini kiriting",
            "maxTokens": "Maks. tokenlar",
            "tokensRange": "256 dan 8192 gacha",
            "tokensHint": "AI javoblarining uzunligini cheklaydi",
            "save": "Saqlash",
            "saved": "AI sozlamalari saqlandi",
            "status": "Holat",
            "keySet": "kalit o'rnatilgan",
            "keyNotSet": "kalit o'rnatilmagan",
            "active": "Faol",
            "modelLabel": "Model:",
            "tokensLabel": "Tokenlar:",
            "inactive": "Nofaol",
            "usedBy": "Foydalaniladi:",
            "featureBio": "Profil matni yaratish",
            "featureAnalysis": "Mijozlar bazasini tahlil qilish",
            "featureBot": "Telegram-bot javoblari",
            "modelDesc": MODEL_DESC_UZ
        }
    },
    "kz": {
        "pageTitle": "Администратор панелі",
        "pageDesc": "Платформа функциялары, пайдаланушылар және анықтамаларды басқару",
        "tabFeatures": "Функциялар",
        "tabUsers": "Пайдаланушылар",
        "tabCatalogs": "Анықтамалар",
        "tabAppearance": "Безендіру",
        "tabBilling": "Биллинг",
        "tabEmail": "Email",
        "tabAI": "АИ",
        "specialtiesTitle": "Мамандықтар анықтамасы",
        "specialtiesDesc": "Шеберлер үшін қызмет түрлері мен мамандықтарды басқару",
        "openSpecialties": "Анықтаманы ашу",
        "tabBrowse": "Анықтама",
        "tabImport": "Импорт",
        "newTypePlaceholder": "Қызмет түрін қосу...",
        "newSpecPlaceholder": "Мамандық қосу...",
        "addSpec": "Мамандық қосу",
        "noTypes": "Қызмет түрлері әлі жоқ. Бірінші қосыңыз.",
        "typeCreated": "Қызмет түрі қосылды",
        "typeDeleted": "Қызмет түрі жойылды",
        "typeDeleteConfirm": "Қызмет түрі мен оның барлық мамандықтарын жою керек пе?",
        "specCreated": "Мамандық қосылды",
        "specDeleted": "Мамандық жойылды",
        "specDeleteConfirm": "Мамандықты жою керек пе?",
        "seedTitle": "Кірістірілген анықтаманы жүктеу",
        "seedDesc": "{{count}} мамандық 9 қызмет түрі бойынша",
        "loadSeed": "Анықтаманы жүктеу",
        "orImport": "немесе өз тізімізді импорттаңыз",
        "importFormat": "Деректер форматы",
        "uploadFile": "Файлды жүктеу",
        "pasteArea": "Деректерді қою",
        "previewBtn": "Алдын ала қарау",
        "previewTitle": "Жазбалар табылды: {{count}}",
        "importBtn": "{{count}} жазбаны импорттау",
        "importSuccess": "Импортталды: {{count}} жаңа жазба",
        "importParseError": "Деректерді оқу қатесі. Форматты тексеріңіз.",
        "importDefaultType": "Жалпы",
        "usersTitle": "Пайдаланушылар",
        "usersDesc": "Платформа пайдаланушылары рөлдерін басқару",
        "openUsers": "Пайдаланушыларды басқару",
        "usersEmpty": "Пайдаланушылар әлі жоқ",
        "makeAdmin": "Әкімші ету",
        "makeAdminSuccess": "Әкімші рөлі берілді",
        "removeAdmin": "Әкімші рөлін алу",
        "removeAdminSuccess": "Әкімші рөлі алынды",
        "roleAdmin": "Әкімші",
        "roleMaster": "Шебер",
        "youLabel": "сіз",
        "cannotSelf": "Өз рөліңізді өзгертуге болмайды",
        "searchUsers": "Атауы немесе email бойынша іздеу...",
        "usersNotFound": "Пайдаланушылар табылмады",
        "disableUser": "Пайдаланушыны өшіру",
        "enableUser": "Пайдаланушыны қосу",
        "userDisabled": "Пайдаланушы өшірілді",
        "userEnabled": "Пайдаланушы қосылды",
        "disabled": "Бұғатталған",
        "active": "Белсенді",
        "userIsDisabled": "Кіру бұғатталған — пайдаланушы кіре алмайды",
        "exportCSV": "CSV-ке экспорт",
        "exportDone": "Экспорт аяқталды",
        "statsTotal": "Барлығы",
        "statsNewMonth": "Айда жаңа",
        "statsPaid": "Ақылы",
        "statsDisabled": "Өшірілген",
        "colUser": "Пайдаланушы",
        "colPlan": "Жоспар",
        "colAdmin": "Әкімші",
        "colStatus": "Күй",
        "userDeleted": "Пайдаланушы жойылды",
        "deleteError": "Жою қатесі",
        "deletedCount": "{{count}} пайдаланушы жойылды",
        "deleteFailedCount": "{{count}} пайдаланушыны жоюда қате",
        "selectedCount": "Таңдалған: {{count}}",
        "deselect": "Алып тастау",
        "deleteSelected": "Жою ({{count}})",
        "selectAll": "Барлығын таңдау",
        "selectUser": "{{name}} таңдау",
        "cannotDeleteAdmin": "Әкімшіні жоюға болмайды",
        "deleteUserAction": "Пайдаланушыны жою",
        "cannotRemoveAdmin": "Әкімші рөлін алуға болмайды",
        "csvName": "Аты",
        "csvEmail": "Email",
        "csvPlan": "Жоспар",
        "csvAdmin": "Әкімші",
        "csvDisabled": "Бұғатталған",
        "csvDate": "Тіркелген күні",
        "csvYes": "иә",
        "csvNo": "жоқ",
        "bulkDeleteTitle": "{{count}} пайдаланушыны жою керек пе?",
        "bulkDeleteDesc": "Таңдалған {{count}} пайдаланушының барлығы біржола жойылады.",
        "deleteUserTitle": "Пайдаланушыны жою керек пе?",
        "deleteUserDesc": "Бұл әрекетті кері қайтаруға болмайды.",
        "deleteIrreversible": "Барлық деректер біржола жойылады.",
        "deleteUserDetails": "Пайдаланушы: {{name}} ({{email}})",
        "deleting": "Жойылуда...",
        "featuresDesc": "Платформа функцияларын қосыңыз және өшіріңіз, минималды кіру жоспарын белгілеңіз",
        "searchFeature": "Функцияны іздеу...",
        "featureEnabled": "Функция қосылды",
        "featureDisabled": "Функция өшірілді",
        "featureEnableHint": "Функцияны қосу",
        "featureDisableHint": "Функцияны өшіру",
        "logoHint": "PNG, JPG, SVG · 5 МБ дейін",
        "fontSize": "Қаріп өлшемі",
        "fontSizeDesc": "Telegram Mini App қоса алғанда бүкіл интерфейсіне әсер етеді",
        "fontSmall": "Кіші",
        "fontMedium": "Орта",
        "fontLarge": "Үлкен",
        "catalogsDesc": "Барлық пайдаланушыларға қол жетімді глобалды платформа анықтамаларын басқару",
        "globalServicesTitle": "Қызметтер анықтамасы",
        "globalServicesDesc": "Шебер профиліне жылдам қосу үшін қызметтердің жаһандық тізімі",
        "openGlobalServices": "Қызметтер анықтамасын ашу",
        "globalProductsTitle": "Тауарлар анықтамасы",
        "globalProductsDesc": "Қойма үшін тауарлар мен материалдардың жаһандық тізімі",
        "openGlobalProducts": "Тауарлар анықтамасын ашу",
        "comingSoon": "Жақында",
        "registeredAt": "Тіркелген",
        "limitMetric": "Метрика",
        "limitHint": "Бұл лимит қажет болмаса жолды өшіріңіз.",
        "emailDesc": "SMTP-сервер және email-хабарландырулар параметрлері",
        "emailGlobalEnabled": "Email-хабарландырулар қосылған",
        "emailGlobalEnabledDesc": "Шеберлерге және клиенттерге хат жіберуге рұқсат беру",
        "smtpTitle": "SMTP сервер",
        "smtpHint": "Ұсынылады: Resend — host smtp.resend.com, port 587, user resend, password = resend.com-дан API key",
        "smtpHost": "Host",
        "smtpPort": "Порт",
        "smtpUser": "Пайдаланушы",
        "smtpPass": "Пароль / API кілт",
        "fromAddress": "Жіберуші email",
        "fromName": "Жіберуші аты",
        "smtpSaved": "SMTP параметрлері сақталды",
        "notifyPerMasterTitle": "Хабарландырулар — шеберлер бойынша",
        "notifyPerMasterDesc": "Әр шебер Параметрлер → Хабарландырулар бөлімінде email-хабарландыруларды қосады және өз үлгісін орната алады",
        "ai": {
            "desc": "АИ-көмекші параметрлері. Профиль мәтінін жасау, клиенттерді талдау және Telegram-бот жауаптары үшін пайдаланылады.",
            "enabled": "АИ қосылған",
            "enabledDesc": "АИ функцияларын пайдалануға рұқсат беру",
            "provider": "Провайдер",
            "customProvider": "Custom (OpenAI-мен үйлесімді)",
            "apiKey": "API кілт",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Кілтті алу",
            "baseUrlHint": "API URL (OpenAI-мен үйлесімді провайдерлер үшін)",
            "model": "Модель",
            "modelPlaceholder": "Модель атауын енгізіңіз",
            "maxTokens": "Макс. токендер",
            "tokensRange": "256-дан 8192-ге дейін",
            "tokensHint": "АИ жауаптарының ұзындығын шектейді",
            "save": "Сақтау",
            "saved": "АИ параметрлері сақталды",
            "status": "Күй",
            "keySet": "кілт орнатылған",
            "keyNotSet": "кілт орнатылмаған",
            "active": "Белсенді",
            "modelLabel": "Модель:",
            "tokensLabel": "Токендер:",
            "inactive": "Белсенді емес",
            "usedBy": "Пайдаланылады:",
            "featureBio": "Профиль мәтінін жасау",
            "featureAnalysis": "Клиенттер базасын талдау",
            "featureBot": "Telegram-бот жауаптары",
            "modelDesc": MODEL_DESC_KZ
        }
    },
    "ky": {
        "pageTitle": "Администратор панели",
        "pageDesc": "Платформа функциялары, колдонуучулар жана маалымдамаларды башкаруу",
        "tabFeatures": "Функциялар",
        "tabUsers": "Колдонуучулар",
        "tabCatalogs": "Маалымдамалар",
        "tabAppearance": "Безендирүү",
        "tabBilling": "Биллинг",
        "tabEmail": "Email",
        "tabAI": "AI",
        "specialtiesTitle": "Адистиктер маалымдамасы",
        "specialtiesDesc": "Чеберлер үчүн иш-аракет түрлөрү менен адистиктерди башкаруу",
        "openSpecialties": "Маалымдаманы ачуу",
        "tabBrowse": "Маалымдама",
        "tabImport": "Импорт",
        "newTypePlaceholder": "Иш-аракет түрүн кошуу...",
        "newSpecPlaceholder": "Адистик кошуу...",
        "addSpec": "Адистик кошуу",
        "noTypes": "Иш-аракет түрлөрү азырынча жок. Биринчисин кошуңуз.",
        "typeCreated": "Иш-аракет түрү кошулду",
        "typeDeleted": "Иш-аракет түрү жойулду",
        "typeDeleteConfirm": "Иш-аракет түрүн жана анын бардык адистиктерин жоюу керекпи?",
        "specCreated": "Адистик кошулду",
        "specDeleted": "Адистик жойулду",
        "specDeleteConfirm": "Адистикти жоюу керекпи?",
        "seedTitle": "Курулган маалымдаманы жүктөө",
        "seedDesc": "{{count}} адистик 9 иш-аракет түрү боюнча",
        "loadSeed": "Маалымдаманы жүктөө",
        "orImport": "же өз тизмеңизди импорттоңуз",
        "importFormat": "Маалымат форматы",
        "uploadFile": "Файлды жүктөө",
        "pasteArea": "Маалыматтарды чаптоо",
        "previewBtn": "Алдын ала кароо",
        "previewTitle": "Жазуулар табылды: {{count}}",
        "importBtn": "{{count}} жазууну импорттоо",
        "importSuccess": "Импортталды: {{count}} жаңы жазуу",
        "importParseError": "Маалыматты окуу катасы. Форматты текшериңиз.",
        "importDefaultType": "Жалпы",
        "usersTitle": "Колдонуучулар",
        "usersDesc": "Платформа колдонуучулары ролдорун башкаруу",
        "openUsers": "Колдонуучуларды башкаруу",
        "usersEmpty": "Колдонуучулар азырынча жок",
        "makeAdmin": "Администратор кылуу",
        "makeAdminSuccess": "Администратор ролу берилди",
        "removeAdmin": "Администратор ролун алуу",
        "removeAdminSuccess": "Администратор ролу алынды",
        "roleAdmin": "Администратор",
        "roleMaster": "Чебер",
        "youLabel": "сиз",
        "cannotSelf": "Өз ролуңузду өзгөртүүгө болбойт",
        "searchUsers": "Аты же email боюнча издөө...",
        "usersNotFound": "Колдонуучулар табылган жок",
        "disableUser": "Колдонуучуну өчүрүү",
        "enableUser": "Колдонуучуну күйгүзүү",
        "userDisabled": "Колдонуучу өчүрүлдү",
        "userEnabled": "Колдонуучу күйгүзүлдү",
        "disabled": "Бөгөттөлгөн",
        "active": "Активдүү",
        "userIsDisabled": "Кирүү бөгөттөлгөн — колдонуучу кире албайт",
        "exportCSV": "CSV-ке экспорт",
        "exportDone": "Экспорт аяктады",
        "statsTotal": "Бардыгы",
        "statsNewMonth": "Айда жаңы",
        "statsPaid": "Акылуу",
        "statsDisabled": "Өчүрүлгөн",
        "colUser": "Колдонуучу",
        "colPlan": "План",
        "colAdmin": "Администратор",
        "colStatus": "Абал",
        "userDeleted": "Колдонуучу жойулду",
        "deleteError": "Жою катасы",
        "deletedCount": "{{count}} колдонуучу жойулду",
        "deleteFailedCount": "{{count}} колдонуучуну жоюуда ката",
        "selectedCount": "Тандалган: {{count}}",
        "deselect": "Алып салуу",
        "deleteSelected": "Жоюу ({{count}})",
        "selectAll": "Баарын тандоо",
        "selectUser": "{{name}} тандоо",
        "cannotDeleteAdmin": "Администраторду жоюуга болбойт",
        "deleteUserAction": "Колдонуучуну жоюу",
        "cannotRemoveAdmin": "Администратор ролун алуу мүмкүн эмес",
        "csvName": "Аты",
        "csvEmail": "Email",
        "csvPlan": "План",
        "csvAdmin": "Администратор",
        "csvDisabled": "Бөгөттөлгөн",
        "csvDate": "Катталган күнү",
        "csvYes": "ооба",
        "csvNo": "жок",
        "bulkDeleteTitle": "{{count}} колдонуучуну жоюу керекпи?",
        "bulkDeleteDesc": "Тандалган {{count}} колдонуучунун баары биротоло жойулат.",
        "deleteUserTitle": "Колдонуучуну жоюу керекпи?",
        "deleteUserDesc": "Бул аракетти кайтарып болбойт.",
        "deleteIrreversible": "Бардык маалыматтар биротоло жойулат.",
        "deleteUserDetails": "Колдонуучу: {{name}} ({{email}})",
        "deleting": "Жойулууда...",
        "featuresDesc": "Платформа функцияларын күйгүзүңүз жана өчүрүңүз, минималдуу кирүү планын белгилеңиз",
        "searchFeature": "Функцияны издөө...",
        "featureEnabled": "Функция күйгүзүлдү",
        "featureDisabled": "Функция өчүрүлдү",
        "featureEnableHint": "Функцияны күйгүзүү",
        "featureDisableHint": "Функцияны өчүрүү",
        "logoHint": "PNG, JPG, SVG · 5 МБ чейин",
        "fontSize": "Шрифт өлчөмү",
        "fontSizeDesc": "Telegram Mini App кошо бүткүл интерфейске таасир этет",
        "fontSmall": "Кичине",
        "fontMedium": "Орто",
        "fontLarge": "Чоң",
        "catalogsDesc": "Бардык колдонуучуларга жеткиликтүү глобалдык платформа маалымдамаларын башкаруу",
        "globalServicesTitle": "Кызматтар маалымдамасы",
        "globalServicesDesc": "Чебер профилине тез кошуу үчүн кызматтардын глобалдык тизмеси",
        "openGlobalServices": "Кызматтар маалымдамасын ачуу",
        "globalProductsTitle": "Товарлар маалымдамасы",
        "globalProductsDesc": "Склад үчүн товарлар жана материалдардын глобалдык тизмеси",
        "openGlobalProducts": "Товарлар маалымдамасын ачуу",
        "comingSoon": "Жакында",
        "registeredAt": "Катталган",
        "limitMetric": "Метрика",
        "limitHint": "Бул лимит керек болбосо, катарды өчүрүңүз.",
        "emailDesc": "SMTP-сервер жана email-билдирүүлөр параметрлери",
        "emailGlobalEnabled": "Email-билдирүүлөр күйгүзүлгөн",
        "emailGlobalEnabledDesc": "Чеберлерге жана кардарларга кат жөнөтүүгө уруксат берүү",
        "smtpTitle": "SMTP сервер",
        "smtpHint": "Сунушталат: Resend — host smtp.resend.com, port 587, user resend, password = resend.com-дан API key",
        "smtpHost": "Host",
        "smtpPort": "Порт",
        "smtpUser": "Колдонуучу",
        "smtpPass": "Сырсөз / API ачкыч",
        "fromAddress": "Жөнөтүүчү email",
        "fromName": "Жөнөтүүчү аты",
        "smtpSaved": "SMTP параметрлери сакталды",
        "notifyPerMasterTitle": "Билдирүүлөр — чеберлер боюнча",
        "notifyPerMasterDesc": "Ар бир чебер Параметрлер → Билдирүүлөр бөлүмүндө email-билдирүүлөрдү күйгүзөт жана өз үлгүсүн орното алат",
        "ai": {
            "desc": "AI-жардамчы параметрлери. Профиль тексти жасоо, кардарларды талдоо жана Telegram-бот жооптору үчүн пайдаланылат.",
            "enabled": "AI күйгүзүлгөн",
            "enabledDesc": "AI функцияларын колдонууга уруксат берүү",
            "provider": "Провайдер",
            "customProvider": "Custom (OpenAI менен шайкеш)",
            "apiKey": "API ачкыч",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Ачкычты алуу",
            "baseUrlHint": "API URL (OpenAI менен шайкеш провайдерлер үчүн)",
            "model": "Модель",
            "modelPlaceholder": "Модель атын киргизиңиз",
            "maxTokens": "Макс. токендер",
            "tokensRange": "256-дан 8192-ге чейин",
            "tokensHint": "AI жооптарынын узундугун чектейт",
            "save": "Сактоо",
            "saved": "AI параметрлери сакталды",
            "status": "Абал",
            "keySet": "ачкыч орнотулган",
            "keyNotSet": "ачкыч орнотулган жок",
            "active": "Активдүү",
            "modelLabel": "Модель:",
            "tokensLabel": "Токендер:",
            "inactive": "Активдүү эмес",
            "usedBy": "Пайдаланылат:",
            "featureBio": "Профиль тексти жасоо",
            "featureAnalysis": "Кардарлар базасын талдоо",
            "featureBot": "Telegram-бот жооптору",
            "modelDesc": MODEL_DESC_KY
        }
    },
    "tg": {
        "pageTitle": "Панели маъмур",
        "pageDesc": "Идоракунии функсияҳо, корбарон ва маълумотномаҳои платформа",
        "tabFeatures": "Функсияҳо",
        "tabUsers": "Корбарон",
        "tabCatalogs": "Маълумотномаҳо",
        "tabAppearance": "Тарроҳӣ",
        "tabBilling": "Биллинг",
        "tabEmail": "Email",
        "tabAI": "АИ",
        "specialtiesTitle": "Маълумотномаи ихтисосҳо",
        "specialtiesDesc": "Идоракунии намудҳои фаъолият ва ихтисосҳо барои устодон",
        "openSpecialties": "Кушодани маълумотнома",
        "tabBrowse": "Маълумотнома",
        "tabImport": "Воридот",
        "newTypePlaceholder": "Илова кардани намуди фаъолият...",
        "newSpecPlaceholder": "Илова кардани ихтисос...",
        "addSpec": "Илова кардани ихтисос",
        "noTypes": "Намудҳои фаъолият ҳанӯз нест. Аввалинро илова кунед.",
        "typeCreated": "Намуди фаъолият илова шуд",
        "typeDeleted": "Намуди фаъолият нест шуд",
        "typeDeleteConfirm": "Намуди фаъолият ва ҳамаи ихтисосҳои онро нест кунем?",
        "specCreated": "Ихтисос илова шуд",
        "specDeleted": "Ихтисос нест шуд",
        "specDeleteConfirm": "Ихтисосро нест кунем?",
        "seedTitle": "Боргузории маълумотномаи дарунсохт",
        "seedDesc": "{{count}} ихтисос аз рӯи 9 намуди фаъолият",
        "loadSeed": "Боргузории маълумотнома",
        "orImport": "ё рӯйхати худро ворид кунед",
        "importFormat": "Формати маълумот",
        "uploadFile": "Боргузории файл",
        "pasteArea": "Часпондани маълумот",
        "previewBtn": "Пешнамоиш",
        "previewTitle": "Сабтҳо ёфт шуданд: {{count}}",
        "importBtn": "Ворид кардани {{count}} сабт",
        "importSuccess": "Ворид карда шуд: {{count}} сабти нав",
        "importParseError": "Хатои хондани маълумот. Форматро санҷед.",
        "importDefaultType": "Умумӣ",
        "usersTitle": "Корбарон",
        "usersDesc": "Идоракунии нақшҳои корбарони платформа",
        "openUsers": "Идоракунии корбарон",
        "usersEmpty": "Корбарон ҳанӯз нест",
        "makeAdmin": "Маъмур кардан",
        "makeAdminSuccess": "Нақши маъмур дода шуд",
        "removeAdmin": "Гирифтани нақши маъмур",
        "removeAdminSuccess": "Нақши маъмур гирифта шуд",
        "roleAdmin": "Маъмур",
        "roleMaster": "Устод",
        "youLabel": "шумо",
        "cannotSelf": "Нақши худро тағйир додан мумкин нест",
        "searchUsers": "Ҷустуҷӯ аз рӯи ном ё email...",
        "usersNotFound": "Корбарон ёфт нашуданд",
        "disableUser": "Ғайрифаъол кардани корбар",
        "enableUser": "Фаъол кардани корбар",
        "userDisabled": "Корбар ғайрифаъол шуд",
        "userEnabled": "Корбар фаъол шуд",
        "disabled": "Манъшуда",
        "active": "Фаъол",
        "userIsDisabled": "Дастрасӣ манъ шудааст — корбар ворид шуда наметавонад",
        "exportCSV": "Содир ба CSV",
        "exportDone": "Содир анҷом ёфт",
        "statsTotal": "Ҳамаи",
        "statsNewMonth": "Нав дар моҳ",
        "statsPaid": "Пардохтшуда",
        "statsDisabled": "Ғайрифаъол",
        "colUser": "Корбар",
        "colPlan": "Нақша",
        "colAdmin": "Маъмур",
        "colStatus": "Вазъият",
        "userDeleted": "Корбар нест шуд",
        "deleteError": "Хатои несткунӣ",
        "deletedCount": "{{count}} корбар нест шуд",
        "deleteFailedCount": "Хатои несткунии {{count}} корбар",
        "selectedCount": "Интихобшуда: {{count}}",
        "deselect": "Бозпас гирифтан",
        "deleteSelected": "Нест кардан ({{count}})",
        "selectAll": "Интихоби ҳамаи",
        "selectUser": "Интихоби {{name}}",
        "cannotDeleteAdmin": "Маъмурро нест кардан мумкин нест",
        "deleteUserAction": "Нест кардани корбар",
        "cannotRemoveAdmin": "Нақши маъмурро гирифтан мумкин нест",
        "csvName": "Ном",
        "csvEmail": "Email",
        "csvPlan": "Нақша",
        "csvAdmin": "Маъмур",
        "csvDisabled": "Манъшуда",
        "csvDate": "Санаи бақайдгирӣ",
        "csvYes": "бале",
        "csvNo": "не",
        "bulkDeleteTitle": "{{count}} корбарро нест кунем?",
        "bulkDeleteDesc": "Ҳамаи {{count}} корбари интихобшуда абадан нест мешаванд.",
        "deleteUserTitle": "Корбарро нест кунем?",
        "deleteUserDesc": "Ин амалро бозгардонидан мумкин нест.",
        "deleteIrreversible": "Ҳамаи маълумот абадан нест мешавад.",
        "deleteUserDetails": "Корбар: {{name}} ({{email}})",
        "deleting": "Нест карда мешавад...",
        "featuresDesc": "Функсияҳои платформаро фаъол ва ғайрифаъол кунед, нақшаи дастрасии минималиро муайян кунед",
        "searchFeature": "Ҷустуҷӯи функсия...",
        "featureEnabled": "Функсия фаъол шуд",
        "featureDisabled": "Функсия ғайрифаъол шуд",
        "featureEnableHint": "Фаъол кардани функсия",
        "featureDisableHint": "Ғайрифаъол кардани функсия",
        "logoHint": "PNG, JPG, SVG · то 5 МБ",
        "fontSize": "Андозаи хат",
        "fontSizeDesc": "Ба тамоми интерфейс, аз ҷумла Telegram Mini App таъсир мерасонад",
        "fontSmall": "Хурд",
        "fontMedium": "Миёна",
        "fontLarge": "Калон",
        "catalogsDesc": "Идоракунии маълумотномаҳои глобалии платформа, ки ба ҳамаи корбарон дастрасанд",
        "globalServicesTitle": "Маълумотномаи хидматҳо",
        "globalServicesDesc": "Рӯйхати глобалии хидматҳо барои илова кардани зуд ба профили устод",
        "openGlobalServices": "Кушодани маълумотномаи хидматҳо",
        "globalProductsTitle": "Маълумотномаи мол",
        "globalProductsDesc": "Рӯйхати глобалии мол ва маводҳо барои анбор",
        "openGlobalProducts": "Кушодани маълумотномаи мол",
        "comingSoon": "Ба зудӣ",
        "registeredAt": "Бақайдгирӣ",
        "limitMetric": "Метрика",
        "limitHint": "Агар ин маҳдудият лозим набошад, сатрро ғайрифаъол кунед.",
        "emailDesc": "Танзимоти SMTP-сервер ва огоҳиҳои email",
        "emailGlobalEnabled": "Огоҳиҳои Email фаъоланд",
        "emailGlobalEnabledDesc": "Иҷозат додан ба фиристодани мактуб ба устодон ва муштариён",
        "smtpTitle": "SMTP сервер",
        "smtpHint": "Тавсия дода мешавад: Resend — host smtp.resend.com, port 587, user resend, password = API key аз resend.com",
        "smtpHost": "Host",
        "smtpPort": "Порт",
        "smtpUser": "Корбар",
        "smtpPass": "Рамз / API кунҷкобӣ",
        "fromAddress": "Email фиристанда",
        "fromName": "Номи фиристанда",
        "smtpSaved": "Танзимоти SMTP сохта шуд",
        "notifyPerMasterTitle": "Огоҳиҳо — аз рӯи устодон",
        "notifyPerMasterDesc": "Ҳар устод огоҳиҳои email-ро дар Танзимот → Огоҳиҳо фаъол мекунад ва метавонад шаблони худро танзим кунад",
        "ai": {
            "desc": "Танзимоти AI-ёрдамчӣ. Барои тавлиди матни профил, таҳлили муштариён ва посухҳои бот-Telegram истифода мешавад.",
            "enabled": "AI фаъол аст",
            "enabledDesc": "Иҷозат додан ба истифодаи функсияҳои AI",
            "provider": "Провайдер",
            "customProvider": "Custom (бо OpenAI мувофиқ)",
            "apiKey": "API кунҷкобӣ",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Гирифтани кунҷкобӣ",
            "baseUrlHint": "API URL (барои провайдерҳои мувофиқ бо OpenAI)",
            "model": "Модел",
            "modelPlaceholder": "Номи моделро ворид кунед",
            "maxTokens": "Макс. токенҳо",
            "tokensRange": "256 то 8192",
            "tokensHint": "Дарозии посухҳои AI-ро маҳдуд мекунад",
            "save": "Нигоҳ доштан",
            "saved": "Танзимоти AI нигоҳ дошта шуд",
            "status": "Вазъият",
            "keySet": "кунҷкобӣ танзим шудааст",
            "keyNotSet": "кунҷкобӣ танзим нашудааст",
            "active": "Фаъол",
            "modelLabel": "Модел:",
            "tokensLabel": "Токенҳо:",
            "inactive": "Ғайрифаъол",
            "usedBy": "Истифода мешавад барои:",
            "featureBio": "Тавлиди матни профил",
            "featureAnalysis": "Таҳлили пойгоҳи муштариён",
            "featureBot": "Посухҳои бот-Telegram",
            "modelDesc": MODEL_DESC_TG
        }
    },
    "by": {
        "pageTitle": "Панэль адміністратара",
        "pageDesc": "Кіраванне функцыямі, карыстальнікамі і даведнікамі платформы",
        "tabFeatures": "Функцыі",
        "tabUsers": "Карыстальнікі",
        "tabCatalogs": "Даведнікі",
        "tabAppearance": "Афармленне",
        "tabBilling": "Білінг",
        "tabEmail": "Email",
        "tabAI": "ІІ",
        "specialtiesTitle": "Даведнік спецыяльнасцей",
        "specialtiesDesc": "Кіраванне відамі дзейнасці і спецыяльнасцямі для майстроў",
        "openSpecialties": "Адкрыць даведнік",
        "tabBrowse": "Даведнік",
        "tabImport": "Імпарт",
        "newTypePlaceholder": "Дадаць від дзейнасці...",
        "newSpecPlaceholder": "Дадаць спецыяльнасць...",
        "addSpec": "Дадаць спецыяльнасць",
        "noTypes": "Відаў дзейнасці пакуль няма. Дадайце першы.",
        "typeCreated": "Від дзейнасці дададзены",
        "typeDeleted": "Від дзейнасці выдалены",
        "typeDeleteConfirm": "Выдаліць від дзейнасці і ўсе яго спецыяльнасці?",
        "specCreated": "Спецыяльнасць дададзена",
        "specDeleted": "Спецыяльнасць выдалена",
        "specDeleteConfirm": "Выдаліць спецыяльнасць?",
        "seedTitle": "Загрузіць убудаваны даведнік",
        "seedDesc": "{{count}} спецыяльнасцей па 9 відах дзейнасці",
        "loadSeed": "Загрузіць даведнік",
        "orImport": "або імпартуйце свой спіс",
        "importFormat": "Фармат даных",
        "uploadFile": "Загрузіць файл",
        "pasteArea": "Уставіць даныя",
        "previewBtn": "Перадпрагляд",
        "previewTitle": "Знойдзена запісаў: {{count}}",
        "importBtn": "Імпартаваць {{count}} запісаў",
        "importSuccess": "Імпартавана: {{count}} новых запісаў",
        "importParseError": "Памылка разбору даных. Праверце фармат.",
        "importDefaultType": "Агульнае",
        "usersTitle": "Карыстальнікі",
        "usersDesc": "Кіраванне ролямі карыстальнікаў платформы",
        "openUsers": "Кіраванне карыстальнікамі",
        "usersEmpty": "Карыстальнікаў пакуль няма",
        "makeAdmin": "Зрабіць адміністратарам",
        "makeAdminSuccess": "Роля адміністратара прызначана",
        "removeAdmin": "Зняць ролю адміністратара",
        "removeAdminSuccess": "Роля адміністратара знята",
        "roleAdmin": "Адміністратар",
        "roleMaster": "Майстар",
        "youLabel": "вы",
        "cannotSelf": "Нельга змяніць сваю ролю",
        "searchUsers": "Пошук па імені або email...",
        "usersNotFound": "Карыстальнікі не знойдзены",
        "disableUser": "Адключыць карыстальніка",
        "enableUser": "Уключыць карыстальніка",
        "userDisabled": "Карыстальнік адключаны",
        "userEnabled": "Карыстальнік уключаны",
        "disabled": "Заблакаваны",
        "active": "Актыўны",
        "userIsDisabled": "Доступ заблакаваны — карыстальнік не можа ўвайсці",
        "exportCSV": "Экспарт у CSV",
        "exportDone": "Экспарт завершаны",
        "statsTotal": "Усяго",
        "statsNewMonth": "Новых за месяц",
        "statsPaid": "Платных",
        "statsDisabled": "Адключаных",
        "colUser": "Карыстальнік",
        "colPlan": "Тарыф",
        "colAdmin": "Адмін",
        "colStatus": "Статус",
        "userDeleted": "Карыстальнік выдалены",
        "deleteError": "Памылка выдалення",
        "deletedCount": "Выдалена {{count}} карыстальнікаў",
        "deleteFailedCount": "Памылка выдалення {{count}} карыстальнікаў",
        "selectedCount": "Абрана: {{count}}",
        "deselect": "Зняць",
        "deleteSelected": "Выдаліць ({{count}})",
        "selectAll": "Выбраць усіх",
        "selectUser": "Выбраць {{name}}",
        "cannotDeleteAdmin": "Адміністратара нельга выдаліць",
        "deleteUserAction": "Выдаліць карыстальніка",
        "cannotRemoveAdmin": "Нельга зняць ролю адміністратара",
        "csvName": "Імя",
        "csvEmail": "Email",
        "csvPlan": "Тарыф",
        "csvAdmin": "Адмін",
        "csvDisabled": "Заблакаваны",
        "csvDate": "Дата рэгістрацыі",
        "csvYes": "так",
        "csvNo": "не",
        "bulkDeleteTitle": "Выдаліць {{count}} карыстальнікаў?",
        "bulkDeleteDesc": "Усе {{count}} абраных карыстальнікаў будуць выдалены назаўжды.",
        "deleteUserTitle": "Выдаліць карыстальніка?",
        "deleteUserDesc": "Гэта дзеянне немагчыма адмяніць.",
        "deleteIrreversible": "Усе даныя будуць выдалены назаўжды.",
        "deleteUserDetails": "Карыстальнік: {{name}} ({{email}})",
        "deleting": "Выдаленне...",
        "featuresDesc": "Уключайце і адключайце функцыі платформы, задавайце мінімальны план доступу",
        "searchFeature": "Пошук функцыі...",
        "featureEnabled": "Функцыя ўключана",
        "featureDisabled": "Функцыя адключана",
        "featureEnableHint": "Уключыць функцыю",
        "featureDisableHint": "Адключыць функцыю",
        "logoHint": "PNG, JPG, SVG · да 5 МБ",
        "fontSize": "Памер шрыфту",
        "fontSizeDesc": "Уплывае на ўвесь інтэрфейс, уключаючы Telegram Mini App",
        "fontSmall": "Малы",
        "fontMedium": "Сярэдні",
        "fontLarge": "Буйны",
        "catalogsDesc": "Кіраванне глабальнымі даведнікамі платформы, даступнымі ўсім карыстальнікам",
        "globalServicesTitle": "Даведнік паслуг",
        "globalServicesDesc": "Глабальны спіс паслуг для хуткага дадання ў профіль майстра",
        "openGlobalServices": "Адкрыць даведнік паслуг",
        "globalProductsTitle": "Даведнік тавараў",
        "globalProductsDesc": "Глабальны спіс тавараў і матэрыялаў для склада",
        "openGlobalProducts": "Адкрыць даведнік тавараў",
        "comingSoon": "Хутка",
        "registeredAt": "Зарэгістраваны",
        "limitMetric": "Метрыка",
        "limitHint": "Адключыце радок, калі гэты ліміт не патрэбны.",
        "emailDesc": "Параметры SMTP-сервера і email-апавяшчэнняў",
        "emailGlobalEnabled": "Email-апавяшчэнні ўключаны",
        "emailGlobalEnabledDesc": "Дазволіць адпраўку лістоў майстрам і кліентам",
        "smtpTitle": "SMTP сервер",
        "smtpHint": "Рэкамендуецца: Resend — host smtp.resend.com, port 587, user resend, password = API key з resend.com",
        "smtpHost": "Host",
        "smtpPort": "Порт",
        "smtpUser": "Карыстальнік",
        "smtpPass": "Пароль / API ключ",
        "fromAddress": "Email адпраўніка",
        "fromName": "Імя адпраўніка",
        "smtpSaved": "Параметры SMTP захаваны",
        "notifyPerMasterTitle": "Апавяшчэнні — па майстрах",
        "notifyPerMasterDesc": "Кожны майстар уключае email-апавяшчэнні ў Параметрах → Апавяшчэнні і можа ўсталяваць свой шаблон",
        "ai": {
            "desc": "Параметры ІІ-памочніка. Выкарыстоўваецца для генерацыі тэксту профілю, аналізу кліентаў і адказаў Telegram-бота.",
            "enabled": "ІІ ўключаны",
            "enabledDesc": "Дазволіць выкарыстанне функцый ІІ",
            "provider": "Правайдар",
            "customProvider": "Custom (сумяшчальны з OpenAI)",
            "apiKey": "API ключ",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Атрымаць ключ на",
            "baseUrlHint": "API URL (для правайдараў сумяшчальных з OpenAI)",
            "model": "Мадэль",
            "modelPlaceholder": "Увядзіце назву мадэлі",
            "maxTokens": "Макс. токенаў",
            "tokensRange": "256 да 8192",
            "tokensHint": "Абмяжоўвае даўжыню адказаў ІІ",
            "save": "Захаваць",
            "saved": "Параметры ІІ захаваны",
            "status": "Статус",
            "keySet": "ключ усталяваны",
            "keyNotSet": "ключ не ўсталяваны",
            "active": "Актыўная",
            "modelLabel": "Мадэль:",
            "tokensLabel": "Токены:",
            "inactive": "Неактыўная",
            "usedBy": "Выкарыстоўваецца для:",
            "featureBio": "Генерацыя тэксту профілю",
            "featureAnalysis": "Аналіз базы кліентаў",
            "featureBot": "Адказы Telegram-бота",
            "modelDesc": MODEL_DESC_BY
        }
    },
    "uk": {
        "pageTitle": "Панель адміністратора",
        "pageDesc": "Управління функціями, користувачами та довідниками платформи",
        "tabFeatures": "Функції",
        "tabUsers": "Користувачі",
        "tabCatalogs": "Довідники",
        "tabAppearance": "Оформлення",
        "tabBilling": "Білінг",
        "tabEmail": "Email",
        "tabAI": "ШІ",
        "specialtiesTitle": "Довідник спеціальностей",
        "specialtiesDesc": "Управління видами діяльності та спеціальностями для майстрів",
        "openSpecialties": "Відкрити довідник",
        "tabBrowse": "Довідник",
        "tabImport": "Імпорт",
        "newTypePlaceholder": "Додати вид діяльності...",
        "newSpecPlaceholder": "Додати спеціальність...",
        "addSpec": "Додати спеціальність",
        "noTypes": "Видів діяльності поки немає. Додайте перший.",
        "typeCreated": "Вид діяльності додано",
        "typeDeleted": "Вид діяльності видалено",
        "typeDeleteConfirm": "Видалити вид діяльності та всі його спеціальності?",
        "specCreated": "Спеціальність додано",
        "specDeleted": "Спеціальність видалено",
        "specDeleteConfirm": "Видалити спеціальність?",
        "seedTitle": "Завантажити вбудований довідник",
        "seedDesc": "{{count}} спеціальностей по 9 видах діяльності",
        "loadSeed": "Завантажити довідник",
        "orImport": "або імпортуйте свій список",
        "importFormat": "Формат даних",
        "uploadFile": "Завантажити файл",
        "pasteArea": "Вставити дані",
        "previewBtn": "Попередній перегляд",
        "previewTitle": "Знайдено записів: {{count}}",
        "importBtn": "Імпортувати {{count}} записів",
        "importSuccess": "Імпортовано: {{count}} нових записів",
        "importParseError": "Помилка розбору даних. Перевірте формат.",
        "importDefaultType": "Загальне",
        "usersTitle": "Користувачі",
        "usersDesc": "Управління ролями користувачів платформи",
        "openUsers": "Управління користувачами",
        "usersEmpty": "Користувачів поки немає",
        "makeAdmin": "Зробити адміністратором",
        "makeAdminSuccess": "Роль адміністратора надано",
        "removeAdmin": "Зняти роль адміністратора",
        "removeAdminSuccess": "Роль адміністратора знято",
        "roleAdmin": "Адміністратор",
        "roleMaster": "Майстер",
        "youLabel": "ви",
        "cannotSelf": "Не можна змінити свою роль",
        "searchUsers": "Пошук за ім'ям або email...",
        "usersNotFound": "Користувачів не знайдено",
        "disableUser": "Вимкнути користувача",
        "enableUser": "Увімкнути користувача",
        "userDisabled": "Користувача вимкнено",
        "userEnabled": "Користувача увімкнено",
        "disabled": "Заблокований",
        "active": "Активний",
        "userIsDisabled": "Доступ заблоковано — користувач не може увійти",
        "exportCSV": "Експорт у CSV",
        "exportDone": "Експорт завершено",
        "statsTotal": "Всього",
        "statsNewMonth": "Нових за місяць",
        "statsPaid": "Платних",
        "statsDisabled": "Вимкнених",
        "colUser": "Користувач",
        "colPlan": "Тариф",
        "colAdmin": "Адмін",
        "colStatus": "Статус",
        "userDeleted": "Користувача видалено",
        "deleteError": "Помилка видалення",
        "deletedCount": "Видалено {{count}} користувачів",
        "deleteFailedCount": "Помилка видалення {{count}} користувачів",
        "selectedCount": "Вибрано: {{count}}",
        "deselect": "Зняти",
        "deleteSelected": "Видалити ({{count}})",
        "selectAll": "Вибрати всіх",
        "selectUser": "Вибрати {{name}}",
        "cannotDeleteAdmin": "Адміністратора не можна видалити",
        "deleteUserAction": "Видалити користувача",
        "cannotRemoveAdmin": "Не можна зняти роль адміністратора",
        "csvName": "Ім'я",
        "csvEmail": "Email",
        "csvPlan": "Тариф",
        "csvAdmin": "Адмін",
        "csvDisabled": "Заблокований",
        "csvDate": "Дата реєстрації",
        "csvYes": "так",
        "csvNo": "ні",
        "bulkDeleteTitle": "Видалити {{count}} користувачів?",
        "bulkDeleteDesc": "Всі {{count}} вибраних користувачів будуть видалені назавжди.",
        "deleteUserTitle": "Видалити користувача?",
        "deleteUserDesc": "Цю дію неможливо скасувати.",
        "deleteIrreversible": "Всі дані будуть видалені назавжди.",
        "deleteUserDetails": "Користувач: {{name}} ({{email}})",
        "deleting": "Видалення...",
        "featuresDesc": "Вмикайте та вимикайте функції платформи, задавайте мінімальний план доступу",
        "searchFeature": "Пошук функції...",
        "featureEnabled": "Функцію увімкнено",
        "featureDisabled": "Функцію вимкнено",
        "featureEnableHint": "Увімкнути функцію",
        "featureDisableHint": "Вимкнути функцію",
        "logoHint": "PNG, JPG, SVG · до 5 МБ",
        "fontSize": "Розмір шрифту",
        "fontSizeDesc": "Впливає на весь інтерфейс, включаючи Telegram Mini App",
        "fontSmall": "Малий",
        "fontMedium": "Середній",
        "fontLarge": "Великий",
        "catalogsDesc": "Управління глобальними довідниками платформи, доступними всім користувачам",
        "globalServicesTitle": "Довідник послуг",
        "globalServicesDesc": "Глобальний список послуг для швидкого додавання у профіль майстра",
        "openGlobalServices": "Відкрити довідник послуг",
        "globalProductsTitle": "Довідник товарів",
        "globalProductsDesc": "Глобальний список товарів та матеріалів для складу",
        "openGlobalProducts": "Відкрити довідник товарів",
        "comingSoon": "Незабаром",
        "registeredAt": "Зареєстрований",
        "limitMetric": "Метрика",
        "limitHint": "Вимкніть рядок, якщо цей ліміт не потрібен.",
        "emailDesc": "Параметри SMTP-сервера та email-сповіщень",
        "emailGlobalEnabled": "Email-сповіщення увімкнено",
        "emailGlobalEnabledDesc": "Дозволити надсилання листів майстрам та клієнтам",
        "smtpTitle": "SMTP сервер",
        "smtpHint": "Рекомендується: Resend — host smtp.resend.com, port 587, user resend, password = API key з resend.com",
        "smtpHost": "Host",
        "smtpPort": "Порт",
        "smtpUser": "Користувач",
        "smtpPass": "Пароль / API ключ",
        "fromAddress": "Email відправника",
        "fromName": "Ім'я відправника",
        "smtpSaved": "Параметри SMTP збережено",
        "notifyPerMasterTitle": "Сповіщення — по майстрах",
        "notifyPerMasterDesc": "Кожен майстер вмикає email-сповіщення в Налаштуваннях → Сповіщення і може встановити свій шаблон",
        "ai": {
            "desc": "Налаштування ШІ-помічника. Використовується для генерації тексту профілю, аналізу клієнтів та відповідей Telegram-бота.",
            "enabled": "ШІ увімкнено",
            "enabledDesc": "Дозволити використання функцій ШІ",
            "provider": "Провайдер",
            "customProvider": "Custom (сумісний з OpenAI)",
            "apiKey": "API ключ",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Отримати ключ на",
            "baseUrlHint": "API URL (для провайдерів сумісних з OpenAI)",
            "model": "Модель",
            "modelPlaceholder": "Введіть назву моделі",
            "maxTokens": "Макс. токенів",
            "tokensRange": "256 до 8192",
            "tokensHint": "Обмежує довжину відповідей ШІ",
            "save": "Зберегти",
            "saved": "Налаштування ШІ збережено",
            "status": "Статус",
            "keySet": "ключ встановлено",
            "keyNotSet": "ключ не встановлено",
            "active": "Активна",
            "modelLabel": "Модель:",
            "tokensLabel": "Токени:",
            "inactive": "Неактивна",
            "usedBy": "Використовується для:",
            "featureBio": "Генерація тексту профілю",
            "featureAnalysis": "Аналіз бази клієнтів",
            "featureBot": "Відповіді Telegram-бота",
            "modelDesc": MODEL_DESC_UK
        }
    },
    "kaa": {
        "pageTitle": "Administrator paneli",
        "pageDesc": "Platforma funksiyaları, paydalanıwshılar hám anıqlama kitapların basqarıw",
        "tabFeatures": "Funksiyalar",
        "tabUsers": "Paydalanıwshılar",
        "tabCatalogs": "Anıqlama kitaplar",
        "tabAppearance": "Bezeniw",
        "tabBilling": "Billing",
        "tabEmail": "Email",
        "tabAI": "AI",
        "specialtiesTitle": "Mamanlıqlar anıqlama kitabı",
        "specialtiesDesc": "Sheberleri ushın is-háreketler hám mamanlıqlardı basqarıw",
        "openSpecialties": "Anıqlama kitabın ashıw",
        "tabBrowse": "Anıqlama kitap",
        "tabImport": "Import",
        "newTypePlaceholder": "Is-háreketlerdi qosıw...",
        "newSpecPlaceholder": "Mamanlıq qosıw...",
        "addSpec": "Mamanlıq qosıw",
        "noTypes": "Is-háreketler áli joq. Birinji qosıń.",
        "typeCreated": "Is-háreketler qosıldı",
        "typeDeleted": "Is-háreketler joyıldı",
        "typeDeleteConfirm": "Is-háreketler hám onıń barlıq mamanlıqların joyw kerek pe?",
        "specCreated": "Mamanlıq qosıldı",
        "specDeleted": "Mamanlıq joyıldı",
        "specDeleteConfirm": "Mamanlıqdı joyw kerek pe?",
        "seedTitle": "Ishki anıqlama kitabın júkletiw",
        "seedDesc": "9 is-háreketler boyınsha {{count}} mamanlıq",
        "loadSeed": "Anıqlama kitabın júkletiw",
        "orImport": "yáki ózińizdıń dizimińizdi import etiń",
        "importFormat": "Maǵlıwmat formati",
        "uploadFile": "Fayldi júkletiw",
        "pasteArea": "Maǵlıwmattı qoyıw",
        "previewBtn": "Aldın kóriw",
        "previewTitle": "Jazıwlar tabıldı: {{count}}",
        "importBtn": "{{count}} jazıwdı import etiw",
        "importSuccess": "Import etildi: {{count}} jańa jazıw",
        "importParseError": "Maǵlıwmat oqıwda qátelik. Formattı tekserıń.",
        "importDefaultType": "Ulıwma",
        "usersTitle": "Paydalanıwshılar",
        "usersDesc": "Platforma paydalanıwshıları rollerın basqarıw",
        "openUsers": "Paydalanıwshılardı basqarıw",
        "usersEmpty": "Paydalanıwshılar áli joq",
        "makeAdmin": "Administrator etiw",
        "makeAdminSuccess": "Administrator roli berildi",
        "removeAdmin": "Administrator rolini alıw",
        "removeAdminSuccess": "Administrator roli alındı",
        "roleAdmin": "Administrator",
        "roleMaster": "Sheber",
        "youLabel": "siz",
        "cannotSelf": "Ózińizdıń roliñizdi ózgertiw múmkin emes",
        "searchUsers": "Atı yáki email boyınsha qıdırıw...",
        "usersNotFound": "Paydalanıwshılar tabılmadı",
        "disableUser": "Paydalanıwshını ósiriw",
        "enableUser": "Paydalanıwshını yaqlaw",
        "userDisabled": "Paydalanıwshı ósiriw",
        "userEnabled": "Paydalanıwshı yaqlawdı",
        "disabled": "Bógeliw",
        "active": "Aktiv",
        "userIsDisabled": "Kirisiw bógelgen — paydalanıwshı kire almadı",
        "exportCSV": "CSV-ke eksport",
        "exportDone": "Eksport amaqlastı",
        "statsTotal": "Barlıǵı",
        "statsNewMonth": "Ayda jańa",
        "statsPaid": "Aqılı",
        "statsDisabled": "Ósiriw",
        "colUser": "Paydalanıwshı",
        "colPlan": "Tarif",
        "colAdmin": "Admin",
        "colStatus": "Jaǵday",
        "userDeleted": "Paydalanıwshı joyıldı",
        "deleteError": "Joyw qáteliği",
        "deletedCount": "{{count}} paydalanıwshı joyıldı",
        "deleteFailedCount": "{{count}} paydalanıwshını joywda qátelik",
        "selectedCount": "Tańlanǵan: {{count}}",
        "deselect": "Alıw",
        "deleteSelected": "Joyw ({{count}})",
        "selectAll": "Barsın tańlaw",
        "selectUser": "{{name}} tańlaw",
        "cannotDeleteAdmin": "Administratordı joyw múmkin emes",
        "deleteUserAction": "Paydalanıwshını joyw",
        "cannotRemoveAdmin": "Administrator rolini alıw múmkin emes",
        "csvName": "Atı",
        "csvEmail": "Email",
        "csvPlan": "Tarif",
        "csvAdmin": "Admin",
        "csvDisabled": "Bógeliw",
        "csvDate": "Dizimge alınǵan sana",
        "csvYes": "hawa",
        "csvNo": "joq",
        "bulkDeleteTitle": "{{count}} paydalanıwshını joyw kerek pe?",
        "bulkDeleteDesc": "Tańlanǵan {{count}} paydalanıwshınıń barsı mángilik joyıladı.",
        "deleteUserTitle": "Paydalanıwshını joyw kerek pe?",
        "deleteUserDesc": "Bul ámeldi qaytarıp bolmadı.",
        "deleteIrreversible": "Barlıq maǵlıwmatlar mángilik joyıladı.",
        "deleteUserDetails": "Paydalanıwshı: {{name}} ({{email}})",
        "deleting": "Joyıwda...",
        "featuresDesc": "Platforma funksiyaların yaqlań hám ósiriń, minimal kirisiw rejasın belgileniz",
        "searchFeature": "Funksiya qıdırıw...",
        "featureEnabled": "Funksiya yaqlawdı",
        "featureDisabled": "Funksiya ósiriw",
        "featureEnableHint": "Funksiyani yaqlaw",
        "featureDisableHint": "Funksiyani ósiriw",
        "logoHint": "PNG, JPG, SVG · 5 MB shekem",
        "fontSize": "Hárip ólshemi",
        "fontSizeDesc": "Telegram Mini App ni qosqanda pútkil interfeys",
        "fontSmall": "Kishkene",
        "fontMedium": "Orta",
        "fontLarge": "Úlken",
        "catalogsDesc": "Barlıq paydalanıwshılarǵa qoljetimli global platforma anıqlama kitapların basqarıw",
        "globalServicesTitle": "Xizmetler anıqlama kitabı",
        "globalServicesDesc": "Sheber profiline tez qosıw ushın xizmetlerdiń global dizimi",
        "openGlobalServices": "Xizmetler anıqlama kitabın ashıw",
        "globalProductsTitle": "Tovarlar anıqlama kitabı",
        "globalProductsDesc": "Ombor ushın tovarlar hám materiallardiń global dizimi",
        "openGlobalProducts": "Tovarlar anıqlama kitabın ashıw",
        "comingSoon": "Tez arada",
        "registeredAt": "Dizimge alınǵan",
        "limitMetric": "Metrika",
        "limitHint": "Bul limit kerek bolmasa, qatardı ósiriń.",
        "emailDesc": "SMTP-server hám email-xabarlawlar sazlamaları",
        "emailGlobalEnabled": "Email-xabarlawlar yaqlı",
        "emailGlobalEnabledDesc": "Sheberlерге hám mijozlarǵa xat jiberiw ushın ruxsat beriw",
        "smtpTitle": "SMTP server",
        "smtpHint": "Usınıladı: Resend — host smtp.resend.com, port 587, user resend, password = resend.com-nan API key",
        "smtpHost": "Host",
        "smtpPort": "Port",
        "smtpUser": "Paydalanıwshı",
        "smtpPass": "Parol / API kalit",
        "fromAddress": "Jiberiwshi email",
        "fromName": "Jiberiwshi atı",
        "smtpSaved": "SMTP sazlamaları saqlandi",
        "notifyPerMasterTitle": "Xabarlawlar — sheberleri boyınsha",
        "notifyPerMasterDesc": "Ár sheber Sazlamalar → Xabarlawlar bóliminde email-xabarlawlardı yaqlaydi hám óziniń shablonın ornatıwi múmkin",
        "ai": {
            "desc": "AI-járdemshisi sazlamaları. Profil mátinin jaratıw, mijozlardı talqılaw hám Telegram-bot jawapları ushın paydalanıladı.",
            "enabled": "AI yaqlı",
            "enabledDesc": "AI funksiyalarınan paydalanıwǵa ruxsat beriw",
            "provider": "Provayder",
            "customProvider": "Custom (OpenAI menen mos)",
            "apiKey": "API kalit",
            "apiKeyPlaceholder": "sk-...",
            "getKeyAt": "Kalitti alıw",
            "baseUrlHint": "API URL (OpenAI menen mos provayderleri ushın)",
            "model": "Model",
            "modelPlaceholder": "Model atın kirisiń",
            "maxTokens": "Maks. tokenlar",
            "tokensRange": "256-dan 8192-ge shekem",
            "tokensHint": "AI jawaplarınıń uzınlıǵın shekleydi",
            "save": "Saqlawdı",
            "saved": "AI sazlamaları saqlandi",
            "status": "Jaǵday",
            "keySet": "kalit ornatılǵan",
            "keyNotSet": "kalit ornatılmaǵan",
            "active": "Aktiv",
            "modelLabel": "Model:",
            "tokensLabel": "Tokenlar:",
            "inactive": "Aktiv emes",
            "usedBy": "Paydalanıladı:",
            "featureBio": "Profil mátinin jaratıw",
            "featureAnalysis": "Mijozlar bazasın talqılaw",
            "featureBot": "Telegram-bot jawapları",
            "modelDesc": MODEL_DESC_KAA
        }
    }
}

langs = list(ADMIN.keys())

for lang in langs:
    path = f'public/locales/{lang}/translation.json'
    with open(path, 'r', encoding='utf-8') as f:
        loc = json.load(f)

    loc['admin'] = ADMIN[lang]

    with open(path, 'w', encoding='utf-8') as f:
        json.dump(loc, f, ensure_ascii=False, indent=2)

    ai_keys = len(ADMIN[lang]['ai'])
    total_keys = len(ADMIN[lang]) + ai_keys + len(ADMIN[lang]['ai']['modelDesc'])
    print(f'{lang}: admin section updated ({total_keys} keys total, {ai_keys} ai keys)')
